version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
      # App
      PORT: ${PORT}
      ENV: ${ENV}
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      LOGS_FORMAT: ${LOGS_FORMAT}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_DIRECTORY: ${LOGS_DIRECTORY}
      LOGS_NAME: ${LOGS_NAME}
      LOGS_LOCAL: ${LOGS_LOCAL}

      # Admin User Details
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
