// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    marina_id,
    type,
    name,
    description,
    email,
    phone
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, marina_id, type, name, description, email, phone, created_at, updated_at, deleted_at
`

type CreateContactParams struct {
	MarinaID    uuid.UUID
	Type        string
	Name        string
	Description *string
	Email       *string
	Phone       *string
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.MarinaID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.Email,
		arg.Phone,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
UPDATE contacts
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, marina_id, type, name, description, email, phone, created_at, updated_at, deleted_at
FROM contacts
WHERE id = $1
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetContactByID(ctx context.Context, id uuid.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, marina_id, type, name, description, email, phone, created_at, updated_at, deleted_at
FROM contacts
WHERE marina_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListContacts(ctx context.Context, marinaID uuid.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, marinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByType = `-- name: ListContactsByType :many
SELECT id, marina_id, type, name, description, email, phone, created_at, updated_at, deleted_at
FROM contacts
WHERE marina_id = $1
    AND type = $2
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListContactsByTypeParams struct {
	MarinaID uuid.UUID
	Type     string
}

func (q *Queries) ListContactsByType(ctx context.Context, arg ListContactsByTypeParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByType, arg.MarinaID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET type = $2,
    name = $3,
    description = $4,
    email = $5,
    phone = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, marina_id, type, name, description, email, phone, created_at, updated_at, deleted_at
`

type UpdateContactParams struct {
	ID          uuid.UUID
	Type        string
	Name        string
	Description *string
	Email       *string
	Phone       *string
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.Email,
		arg.Phone,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
