// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: criteria.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCriteria = `-- name: CreateCriteria :one
INSERT INTO criteria (
    marina_id,
    name,
    description,
    criteria
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, marina_id, name, description, criteria, created_at, updated_at, deleted_at
`

type CreateCriteriaParams struct {
	MarinaID    uuid.UUID
	Name        string
	Description *string
	Criteria    []byte
}

func (q *Queries) CreateCriteria(ctx context.Context, arg CreateCriteriaParams) (Criterium, error) {
	row := q.db.QueryRow(ctx, createCriteria,
		arg.MarinaID,
		arg.Name,
		arg.Description,
		arg.Criteria,
	)
	var i Criterium
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.Criteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCriteria = `-- name: DeleteCriteria :exec
UPDATE criteria
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteCriteria(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCriteria, id)
	return err
}

const getCriteriaByID = `-- name: GetCriteriaByID :one
SELECT id, marina_id, name, description, criteria, created_at, updated_at, deleted_at
FROM criteria
WHERE id = $1
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCriteriaByID(ctx context.Context, id uuid.UUID) (Criterium, error) {
	row := q.db.QueryRow(ctx, getCriteriaByID, id)
	var i Criterium
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.Criteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCriteriaCount = `-- name: GetCriteriaCount :one
SELECT COUNT(*)
FROM criteria
WHERE marina_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCriteriaCount(ctx context.Context, marinaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getCriteriaCount, marinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCriteria = `-- name: ListCriteria :many
SELECT id, marina_id, name, description, criteria, created_at, updated_at, deleted_at
FROM criteria
WHERE marina_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCriteria(ctx context.Context, marinaID uuid.UUID) ([]Criterium, error) {
	rows, err := q.db.Query(ctx, listCriteria, marinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Criterium
	for rows.Next() {
		var i Criterium
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.Criteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCriteriaPaginated = `-- name: ListCriteriaPaginated :many
SELECT id, marina_id, name, description, criteria, created_at, updated_at, deleted_at
FROM criteria
WHERE marina_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCriteriaPaginatedParams struct {
	MarinaID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListCriteriaPaginated(ctx context.Context, arg ListCriteriaPaginatedParams) ([]Criterium, error) {
	rows, err := q.db.Query(ctx, listCriteriaPaginated, arg.MarinaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Criterium
	for rows.Next() {
		var i Criterium
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.Criteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCriteriaByName = `-- name: SearchCriteriaByName :many
SELECT id, marina_id, name, description, criteria, created_at, updated_at, deleted_at
FROM criteria
WHERE marina_id = $1
    AND name ILIKE '%' || $2 || '%'
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

type SearchCriteriaByNameParams struct {
	MarinaID uuid.UUID
	Column2  *string
}

func (q *Queries) SearchCriteriaByName(ctx context.Context, arg SearchCriteriaByNameParams) ([]Criterium, error) {
	rows, err := q.db.Query(ctx, searchCriteriaByName, arg.MarinaID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Criterium
	for rows.Next() {
		var i Criterium
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.Criteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCriteriaByNamePaginated = `-- name: SearchCriteriaByNamePaginated :many
SELECT id, marina_id, name, description, criteria, created_at, updated_at, deleted_at
FROM criteria
WHERE marina_id = $1
    AND name ILIKE '%' || $2 || '%'
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchCriteriaByNamePaginatedParams struct {
	MarinaID uuid.UUID
	Column2  *string
	Limit    int32
	Offset   int32
}

func (q *Queries) SearchCriteriaByNamePaginated(ctx context.Context, arg SearchCriteriaByNamePaginatedParams) ([]Criterium, error) {
	rows, err := q.db.Query(ctx, searchCriteriaByNamePaginated,
		arg.MarinaID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Criterium
	for rows.Next() {
		var i Criterium
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.Criteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCriteria = `-- name: UpdateCriteria :one
UPDATE criteria
SET name = $2,
    description = $3,
    criteria = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, marina_id, name, description, criteria, created_at, updated_at, deleted_at
`

type UpdateCriteriaParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Criteria    []byte
}

func (q *Queries) UpdateCriteria(ctx context.Context, arg UpdateCriteriaParams) (Criterium, error) {
	row := q.db.QueryRow(ctx, updateCriteria,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Criteria,
	)
	var i Criterium
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.Criteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
