// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customer_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomerSettings = `-- name: CreateCustomerSettings :one
INSERT INTO customer_settings (
    marina_id,
    customer_id,
    enable_portal
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, marina_id, customer_id, enable_portal, created_at, updated_at, deleted_at
`

type CreateCustomerSettingsParams struct {
	MarinaID     uuid.UUID
	CustomerID   string
	EnablePortal *bool
}

func (q *Queries) CreateCustomerSettings(ctx context.Context, arg CreateCustomerSettingsParams) (CustomerSetting, error) {
	row := q.db.QueryRow(ctx, createCustomerSettings, arg.MarinaID, arg.CustomerID, arg.EnablePortal)
	var i CustomerSetting
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.CustomerID,
		&i.EnablePortal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerSettings = `-- name: GetCustomerSettings :one
SELECT id, marina_id, customer_id, enable_portal, created_at, updated_at, deleted_at
FROM customer_settings
WHERE marina_id = $1 AND customer_id = $2
`

type GetCustomerSettingsParams struct {
	MarinaID   uuid.UUID
	CustomerID string
}

func (q *Queries) GetCustomerSettings(ctx context.Context, arg GetCustomerSettingsParams) (CustomerSetting, error) {
	row := q.db.QueryRow(ctx, getCustomerSettings, arg.MarinaID, arg.CustomerID)
	var i CustomerSetting
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.CustomerID,
		&i.EnablePortal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCustomerSettings = `-- name: UpdateCustomerSettings :one
UPDATE customer_settings
SET enable_portal = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE marina_id = $1 AND customer_id = $2
RETURNING id, marina_id, customer_id, enable_portal, created_at, updated_at, deleted_at
`

type UpdateCustomerSettingsParams struct {
	MarinaID     uuid.UUID
	CustomerID   string
	EnablePortal *bool
}

func (q *Queries) UpdateCustomerSettings(ctx context.Context, arg UpdateCustomerSettingsParams) (CustomerSetting, error) {
	row := q.db.QueryRow(ctx, updateCustomerSettings, arg.MarinaID, arg.CustomerID, arg.EnablePortal)
	var i CustomerSetting
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.CustomerID,
		&i.EnablePortal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertCustomerSettings = `-- name: UpsertCustomerSettings :one
INSERT INTO customer_settings (
    marina_id,
    customer_id,
    enable_portal
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (marina_id, customer_id) DO UPDATE
SET enable_portal = EXCLUDED.enable_portal,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, marina_id, customer_id, enable_portal, created_at, updated_at, deleted_at
`

type UpsertCustomerSettingsParams struct {
	MarinaID     uuid.UUID
	CustomerID   string
	EnablePortal *bool
}

func (q *Queries) UpsertCustomerSettings(ctx context.Context, arg UpsertCustomerSettingsParams) (CustomerSetting, error) {
	row := q.db.QueryRow(ctx, upsertCustomerSettings, arg.MarinaID, arg.CustomerID, arg.EnablePortal)
	var i CustomerSetting
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.CustomerID,
		&i.EnablePortal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
