// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dme_sysids.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDMESysID = `-- name: CreateDMESysID :one
INSERT INTO dme_sysids (
        organization_id,
        marina_id,
        name,
        description,
        system_id,
        is_active
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
RETURNING id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
`

type CreateDMESysIDParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Name           string
	Description    *string
	SystemID       string
	IsActive       *bool
}

func (q *Queries) CreateDMESysID(ctx context.Context, arg CreateDMESysIDParams) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, createDMESysID,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Name,
		arg.Description,
		arg.SystemID,
		arg.IsActive,
	)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDMESysIDWithoutMarinaID = `-- name: CreateDMESysIDWithoutMarinaID :one
INSERT INTO dme_sysids (
    organization_id,
    name,
    description,
    system_id,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
`

type CreateDMESysIDWithoutMarinaIDParams struct {
	OrganizationID uuid.UUID
	Name           string
	Description    *string
	SystemID       string
	IsActive       *bool
}

func (q *Queries) CreateDMESysIDWithoutMarinaID(ctx context.Context, arg CreateDMESysIDWithoutMarinaIDParams) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, createDMESysIDWithoutMarinaID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.SystemID,
		arg.IsActive,
	)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDMESysID = `-- name: DeleteDMESysID :exec
UPDATE dme_sysids
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteDMESysID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDMESysID, id)
	return err
}

const getDMESysIDByID = `-- name: GetDMESysIDByID :one
SELECT id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
FROM dme_sysids
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetDMESysIDByID(ctx context.Context, id uuid.UUID) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, getDMESysIDByID, id)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDMESysIDByIDWithDeleted = `-- name: GetDMESysIDByIDWithDeleted :one
SELECT id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
FROM dme_sysids
WHERE id = $1
`

func (q *Queries) GetDMESysIDByIDWithDeleted(ctx context.Context, id uuid.UUID) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, getDMESysIDByIDWithDeleted, id)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDMESysIDByMarinaID = `-- name: GetDMESysIDByMarinaID :one
SELECT id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
FROM dme_sysids
WHERE marina_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetDMESysIDByMarinaID(ctx context.Context, marinaID uuid.UUID) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, getDMESysIDByMarinaID, marinaID)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDMESysIDByOrgAndSystemID = `-- name: GetDMESysIDByOrgAndSystemID :one
SELECT id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
FROM dme_sysids
WHERE organization_id = $1
    AND system_id = $2
    AND deleted_at IS NULL
`

type GetDMESysIDByOrgAndSystemIDParams struct {
	OrganizationID uuid.UUID
	SystemID       string
}

func (q *Queries) GetDMESysIDByOrgAndSystemID(ctx context.Context, arg GetDMESysIDByOrgAndSystemIDParams) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, getDMESysIDByOrgAndSystemID, arg.OrganizationID, arg.SystemID)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDMESysIDBySystemID = `-- name: GetDMESysIDBySystemID :one
SELECT id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
FROM dme_sysids
WHERE system_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetDMESysIDBySystemID(ctx context.Context, systemID string) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, getDMESysIDBySystemID, systemID)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDMESysIDsByOrgID = `-- name: GetDMESysIDsByOrgID :many
SELECT id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
FROM dme_sysids
WHERE organization_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetDMESysIDsByOrgID(ctx context.Context, organizationID uuid.UUID) ([]DmeSysid, error) {
	rows, err := q.db.Query(ctx, getDMESysIDsByOrgID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DmeSysid
	for rows.Next() {
		var i DmeSysid
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.SystemID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDMESysIdBySystemID = `-- name: GetDMESysIdBySystemID :one
SELECT d.id, d.organization_id, d.marina_id, d.name, d.description, d.system_id, d.is_active, d.created_at, d.updated_at, d.deleted_at
FROM dme_sysids d
WHERE d.system_id = $1
    AND d.deleted_at IS NULL
`

func (q *Queries) GetDMESysIdBySystemID(ctx context.Context, systemID string) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, getDMESysIdBySystemID, systemID)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteDMESysID = `-- name: HardDeleteDMESysID :exec
DELETE FROM dme_sysids
WHERE id = $1
`

func (q *Queries) HardDeleteDMESysID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteDMESysID, id)
	return err
}

const linkDMESysIDToMarina = `-- name: LinkDMESysIDToMarina :one
UPDATE dme_sysids
SET marina_id = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
`

type LinkDMESysIDToMarinaParams struct {
	ID       uuid.UUID
	MarinaID uuid.UUID
}

func (q *Queries) LinkDMESysIDToMarina(ctx context.Context, arg LinkDMESysIDToMarinaParams) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, linkDMESysIDToMarina, arg.ID, arg.MarinaID)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDMESysIDs = `-- name: ListDMESysIDs :many
SELECT id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
FROM dme_sysids
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDMESysIDs(ctx context.Context) ([]DmeSysid, error) {
	rows, err := q.db.Query(ctx, listDMESysIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DmeSysid
	for rows.Next() {
		var i DmeSysid
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.SystemID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkDMESysIDFromMarina = `-- name: UnlinkDMESysIDFromMarina :one
UPDATE dme_sysids
SET marina_id = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) UnlinkDMESysIDFromMarina(ctx context.Context, id uuid.UUID) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, unlinkDMESysIDFromMarina, id)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDMESysID = `-- name: UpdateDMESysID :one
UPDATE dme_sysids
SET organization_id = $2,
    marina_id = $3,
    name = $4,
    description = $5,
    system_id = $6,
    is_active = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
`

type UpdateDMESysIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Name           string
	Description    *string
	SystemID       string
	IsActive       *bool
}

func (q *Queries) UpdateDMESysID(ctx context.Context, arg UpdateDMESysIDParams) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, updateDMESysID,
		arg.ID,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Name,
		arg.Description,
		arg.SystemID,
		arg.IsActive,
	)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDMESysID = `-- name: UpsertDMESysID :one
INSERT INTO dme_sysids (
    organization_id,
    marina_id,
    name,
    description,
    system_id,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (organization_id, system_id) 
DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, organization_id, marina_id, name, description, system_id, is_active, created_at, updated_at, deleted_at
`

type UpsertDMESysIDParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Name           string
	Description    *string
	SystemID       string
	IsActive       *bool
}

func (q *Queries) UpsertDMESysID(ctx context.Context, arg UpsertDMESysIDParams) (DmeSysid, error) {
	row := q.db.QueryRow(ctx, upsertDMESysID,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Name,
		arg.Description,
		arg.SystemID,
		arg.IsActive,
	)
	var i DmeSysid
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.SystemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
