// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dme_credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDMECredentials = `-- name: CreateDMECredentials :one
INSERT INTO dme_credentials (
        organization_id,
        username,
        password,
        is_old_api,
        access_token,
        refresh_token,
        expiry_date
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
RETURNING id, organization_id, username, password, is_old_api, access_token, refresh_token, expiry_date, created_at, updated_at, deleted_at
`

type CreateDMECredentialsParams struct {
	OrganizationID uuid.UUID
	Username       string
	Password       *string
	IsOldApi       *bool
	AccessToken    *string
	RefreshToken   *string
	ExpiryDate     pgtype.Timestamp
}

func (q *Queries) CreateDMECredentials(ctx context.Context, arg CreateDMECredentialsParams) (DmeCredential, error) {
	row := q.db.QueryRow(ctx, createDMECredentials,
		arg.OrganizationID,
		arg.Username,
		arg.Password,
		arg.IsOldApi,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiryDate,
	)
	var i DmeCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.Password,
		&i.IsOldApi,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDMECredentials = `-- name: DeleteDMECredentials :exec
UPDATE dme_credentials
SET deleted_at = CURRENT_TIMESTAMP
WHERE organization_id = $1
`

func (q *Queries) DeleteDMECredentials(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDMECredentials, organizationID)
	return err
}

const getDMECredentialsByOrgID = `-- name: GetDMECredentialsByOrgID :one
SELECT id, organization_id, username, password, is_old_api, access_token, refresh_token, expiry_date, created_at, updated_at, deleted_at
FROM dme_credentials
WHERE organization_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetDMECredentialsByOrgID(ctx context.Context, organizationID uuid.UUID) (DmeCredential, error) {
	row := q.db.QueryRow(ctx, getDMECredentialsByOrgID, organizationID)
	var i DmeCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.Password,
		&i.IsOldApi,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDMECredentialsByOrgIDWithDeleted = `-- name: GetDMECredentialsByOrgIDWithDeleted :one
SELECT id, organization_id, username, password, is_old_api, access_token, refresh_token, expiry_date, created_at, updated_at, deleted_at
FROM dme_credentials
WHERE organization_id = $1
`

func (q *Queries) GetDMECredentialsByOrgIDWithDeleted(ctx context.Context, organizationID uuid.UUID) (DmeCredential, error) {
	row := q.db.QueryRow(ctx, getDMECredentialsByOrgIDWithDeleted, organizationID)
	var i DmeCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.Password,
		&i.IsOldApi,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteDMECredentials = `-- name: HardDeleteDMECredentials :exec
DELETE FROM dme_credentials
WHERE organization_id = $1
`

func (q *Queries) HardDeleteDMECredentials(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteDMECredentials, organizationID)
	return err
}

const updateDMECredentials = `-- name: UpdateDMECredentials :one
UPDATE dme_credentials
SET username = $2,
    password = $3,
    is_old_api = $4,
    access_token = $5,
    refresh_token = $6,
    expiry_date = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE organization_id = $1
RETURNING id, organization_id, username, password, is_old_api, access_token, refresh_token, expiry_date, created_at, updated_at, deleted_at
`

type UpdateDMECredentialsParams struct {
	OrganizationID uuid.UUID
	Username       string
	Password       *string
	IsOldApi       *bool
	AccessToken    *string
	RefreshToken   *string
	ExpiryDate     pgtype.Timestamp
}

func (q *Queries) UpdateDMECredentials(ctx context.Context, arg UpdateDMECredentialsParams) (DmeCredential, error) {
	row := q.db.QueryRow(ctx, updateDMECredentials,
		arg.OrganizationID,
		arg.Username,
		arg.Password,
		arg.IsOldApi,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiryDate,
	)
	var i DmeCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.Password,
		&i.IsOldApi,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDMEToken = `-- name: UpdateDMEToken :one
UPDATE dme_credentials
SET access_token = $2,
    refresh_token = $3,
    expiry_date = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE organization_id = $1
RETURNING id, organization_id, username, password, is_old_api, access_token, refresh_token, expiry_date, created_at, updated_at, deleted_at
`

type UpdateDMETokenParams struct {
	OrganizationID uuid.UUID
	AccessToken    *string
	RefreshToken   *string
	ExpiryDate     pgtype.Timestamp
}

func (q *Queries) UpdateDMEToken(ctx context.Context, arg UpdateDMETokenParams) (DmeCredential, error) {
	row := q.db.QueryRow(ctx, updateDMEToken,
		arg.OrganizationID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiryDate,
	)
	var i DmeCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Username,
		&i.Password,
		&i.IsOldApi,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
