// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    marina_id,
    entity_type,
    entity_id,
    file_name,
    file_type,
    file_path,
    file_size,
    public
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, marina_id, entity_type, entity_id, file_name, file_type, file_path, file_size, created_at, updated_at, public
`

type CreateDocumentParams struct {
	MarinaID   uuid.UUID
	EntityType string
	EntityID   string
	FileName   string
	FileType   string
	FilePath   string
	FileSize   int64
	Public     bool
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.MarinaID,
		arg.EntityType,
		arg.EntityID,
		arg.FileName,
		arg.FileType,
		arg.FilePath,
		arg.FileSize,
		arg.Public,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.FileType,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, marina_id, entity_type, entity_id, file_name, file_type, file_path, file_size, created_at, updated_at, public FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.FileType,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
	)
	return i, err
}

const listDocumentsByEntity = `-- name: ListDocumentsByEntity :many
SELECT id, marina_id, entity_type, entity_id, file_name, file_type, file_path, file_size, created_at, updated_at, public
FROM documents
WHERE marina_id = $1
AND entity_type = $2
AND entity_id = $3
ORDER BY created_at DESC
`

type ListDocumentsByEntityParams struct {
	MarinaID   uuid.UUID
	EntityType string
	EntityID   string
}

func (q *Queries) ListDocumentsByEntity(ctx context.Context, arg ListDocumentsByEntityParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByEntity, arg.MarinaID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.EntityType,
			&i.EntityID,
			&i.FileName,
			&i.FileType,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByEntityWithVisibility = `-- name: ListDocumentsByEntityWithVisibility :many
SELECT id, marina_id, entity_type, entity_id, file_name, file_type, file_path, file_size, created_at, updated_at, public
FROM documents
WHERE marina_id = $1
AND entity_type = $2
AND entity_id = $3
AND ($4 = true OR public = true)
ORDER BY created_at DESC
`

type ListDocumentsByEntityWithVisibilityParams struct {
	MarinaID   uuid.UUID
	EntityType string
	EntityID   string
	Column4    interface{}
}

func (q *Queries) ListDocumentsByEntityWithVisibility(ctx context.Context, arg ListDocumentsByEntityWithVisibilityParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByEntityWithVisibility,
		arg.MarinaID,
		arg.EntityType,
		arg.EntityID,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.EntityType,
			&i.EntityID,
			&i.FileName,
			&i.FileType,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByMarina = `-- name: ListDocumentsByMarina :many
SELECT id, marina_id, entity_type, entity_id, file_name, file_type, file_path, file_size, created_at, updated_at, public
FROM documents
WHERE marina_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByMarinaParams struct {
	MarinaID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListDocumentsByMarina(ctx context.Context, arg ListDocumentsByMarinaParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByMarina, arg.MarinaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.EntityType,
			&i.EntityID,
			&i.FileName,
			&i.FileType,
			&i.FilePath,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET
    file_name = $2,
    file_type = $3,
    file_path = $4,
    file_size = $5,
    public = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, marina_id, entity_type, entity_id, file_name, file_type, file_path, file_size, created_at, updated_at, public
`

type UpdateDocumentParams struct {
	ID       uuid.UUID
	FileName string
	FileType string
	FilePath string
	FileSize int64
	Public   bool
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.FileName,
		arg.FileType,
		arg.FilePath,
		arg.FileSize,
		arg.Public,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.FileType,
		&i.FilePath,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Public,
	)
	return i, err
}
