// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: esign_submissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEsignSubmissionsByDocument = `-- name: CountEsignSubmissionsByDocument :one
SELECT COUNT(*)
FROM esign_submissions
WHERE document_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountEsignSubmissionsByDocument(ctx context.Context, documentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsByMarina = `-- name: CountEsignSubmissionsByMarina :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND deleted_at IS NULL
`

type CountEsignSubmissionsByMarinaParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
}

func (q *Queries) CountEsignSubmissionsByMarina(ctx context.Context, arg CountEsignSubmissionsByMarinaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByMarina, arg.OrganizationID, arg.MarinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsByMarinaFiltered = `-- name: CountEsignSubmissionsByMarinaFiltered :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR customer_id = $3)
  AND ($4 = '' OR status = $4)
`

type CountEsignSubmissionsByMarinaFilteredParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
	Column4        interface{}
}

func (q *Queries) CountEsignSubmissionsByMarinaFiltered(ctx context.Context, arg CountEsignSubmissionsByMarinaFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByMarinaFiltered,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsByStatus = `-- name: CountEsignSubmissionsByStatus :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND status = $3
    AND deleted_at IS NULL
`

type CountEsignSubmissionsByStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Status         string
}

func (q *Queries) CountEsignSubmissionsByStatus(ctx context.Context, arg CountEsignSubmissionsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByStatus, arg.OrganizationID, arg.MarinaID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsFilteredByDocument = `-- name: CountEsignSubmissionsFilteredByDocument :one
SELECT COUNT(*)
FROM esign_submissions
WHERE document_id = $1
  AND deleted_at IS NULL
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR customer_id = $3)
  AND ($4 = '' OR LOWER(email) LIKE LOWER('%' || $4 || '%'))
  AND ($5 = '' OR LOWER(name) LIKE LOWER('%' || $5 || '%'))
`

type CountEsignSubmissionsFilteredByDocumentParams struct {
	DocumentID uuid.UUID
	Column2    interface{}
	Column3    interface{}
	Column4    interface{}
	Column5    interface{}
}

func (q *Queries) CountEsignSubmissionsFilteredByDocument(ctx context.Context, arg CountEsignSubmissionsFilteredByDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsFilteredByDocument,
		arg.DocumentID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsFilteredByStatus = `-- name: CountEsignSubmissionsFilteredByStatus :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND status = $3
  AND deleted_at IS NULL
  AND ($4 = '' OR customer_id = $4)
  AND ($5 = '' OR LOWER(email) LIKE LOWER('%' || $5 || '%'))
  AND ($6 = '' OR LOWER(name) LIKE LOWER('%' || $6 || '%'))
  AND ($7 = '' OR document_id = $7::uuid)
`

type CountEsignSubmissionsFilteredByStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Status         string
	Column4        interface{}
	Column5        interface{}
	Column6        interface{}
	Column7        interface{}
}

func (q *Queries) CountEsignSubmissionsFilteredByStatus(ctx context.Context, arg CountEsignSubmissionsFilteredByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsFilteredByStatus,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Status,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsWithFilters = `-- name: CountEsignSubmissionsWithFilters :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR status = $3)
  AND ($4 = '' OR (
    LOWER(email) LIKE LOWER('%' || $4 || '%') OR
    LOWER(name) LIKE LOWER('%' || $4 || '%') OR
    LOWER(status) LIKE LOWER('%' || $4 || '%') OR
    LOWER(customer_id) LIKE LOWER('%' || $4 || '%')
  ))
  AND ($5 = '' OR customer_id = $5)
`

type CountEsignSubmissionsWithFiltersParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
	Column4        interface{}
	Column5        interface{}
}

func (q *Queries) CountEsignSubmissionsWithFilters(ctx context.Context, arg CountEsignSubmissionsWithFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsWithFilters,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEsignSubmission = `-- name: CreateEsignSubmission :one
INSERT INTO esign_submissions (
    organization_id,
    marina_id,
    document_id,
    status,
    blob_url,
    blob_metadata,
    customer_id,
    email,
    name,
    attachment_required,
    reply_to,
    custom_message,
    is_multiple_signature
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
`

type CreateEsignSubmissionParams struct {
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	DocumentID          uuid.UUID
	Status              string
	BlobUrl             string
	BlobMetadata        []byte
	CustomerID          *string
	Email               string
	Name                *string
	AttachmentRequired  *bool
	ReplyTo             *string
	CustomMessage       *string
	IsMultipleSignature bool
}

func (q *Queries) CreateEsignSubmission(ctx context.Context, arg CreateEsignSubmissionParams) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, createEsignSubmission,
		arg.OrganizationID,
		arg.MarinaID,
		arg.DocumentID,
		arg.Status,
		arg.BlobUrl,
		arg.BlobMetadata,
		arg.CustomerID,
		arg.Email,
		arg.Name,
		arg.AttachmentRequired,
		arg.ReplyTo,
		arg.CustomMessage,
		arg.IsMultipleSignature,
	)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.AttachmentRequired,
		&i.ReplyTo,
		&i.CustomMessage,
		&i.IsMultipleSignature,
	)
	return i, err
}

const getEsignSubmissionByID = `-- name: GetEsignSubmissionByID :one
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetEsignSubmissionByID(ctx context.Context, id uuid.UUID) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, getEsignSubmissionByID, id)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.AttachmentRequired,
		&i.ReplyTo,
		&i.CustomMessage,
		&i.IsMultipleSignature,
	)
	return i, err
}

const getEsignSubmissionWithSigners = `-- name: GetEsignSubmissionWithSigners :many
SELECT 
    es.id, es.organization_id, es.marina_id, es.document_id, es.status, es.blob_url, es.blob_metadata, es.customer_id, es.email, es.created_at, es.updated_at, es.deleted_at, es.name, es.attachment_required, es.reply_to, es.custom_message, es.is_multiple_signature,
    ess.id as signer_id,
    ess.email as signer_email,
    ess.name as signer_name,
    ess.sign_order,
    ess.status as signer_status,
    ess.signed_at,
    ess.declined_at,
    ess.declined_reason,
    ess.created_at as signer_created_at,
    ess.updated_at as signer_updated_at
FROM esign_submissions es
LEFT JOIN esign_submission_signers ess ON es.id = ess.submission_id AND ess.deleted_at IS NULL
WHERE es.id = $1
    AND es.deleted_at IS NULL
ORDER BY ess.sign_order ASC
`

type GetEsignSubmissionWithSignersRow struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	DocumentID          uuid.UUID
	Status              string
	BlobUrl             string
	BlobMetadata        []byte
	CustomerID          *string
	Email               string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	Name                *string
	AttachmentRequired  *bool
	ReplyTo             *string
	CustomMessage       *string
	IsMultipleSignature bool
	SignerID            uuid.UUID
	SignerEmail         *string
	SignerName          *string
	SignOrder           *int32
	SignerStatus        *string
	SignedAt            pgtype.Timestamp
	DeclinedAt          pgtype.Timestamp
	DeclinedReason      *string
	SignerCreatedAt     pgtype.Timestamp
	SignerUpdatedAt     pgtype.Timestamp
}

func (q *Queries) GetEsignSubmissionWithSigners(ctx context.Context, id uuid.UUID) ([]GetEsignSubmissionWithSignersRow, error) {
	rows, err := q.db.Query(ctx, getEsignSubmissionWithSigners, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEsignSubmissionWithSignersRow
	for rows.Next() {
		var i GetEsignSubmissionWithSignersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
			&i.SignerID,
			&i.SignerEmail,
			&i.SignerName,
			&i.SignOrder,
			&i.SignerStatus,
			&i.SignedAt,
			&i.DeclinedAt,
			&i.DeclinedReason,
			&i.SignerCreatedAt,
			&i.SignerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteEsignSubmission = `-- name: HardDeleteEsignSubmission :exec
DELETE FROM esign_submissions
WHERE id = $1
`

func (q *Queries) HardDeleteEsignSubmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteEsignSubmission, id)
	return err
}

const listEsignSubmissionsByCustomerID = `-- name: ListEsignSubmissionsByCustomerID :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE customer_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEsignSubmissionsByCustomerIDParams struct {
	CustomerID *string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListEsignSubmissionsByCustomerID(ctx context.Context, arg ListEsignSubmissionsByCustomerIDParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByCustomerID, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByDocument = `-- name: ListEsignSubmissionsByDocument :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE document_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEsignSubmissionsByDocumentParams struct {
	DocumentID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListEsignSubmissionsByDocument(ctx context.Context, arg ListEsignSubmissionsByDocumentParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByDocument, arg.DocumentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByMarina = `-- name: ListEsignSubmissionsByMarina :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListEsignSubmissionsByMarinaParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignSubmissionsByMarina(ctx context.Context, arg ListEsignSubmissionsByMarinaParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByMarina,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByMarinaFiltered = `-- name: ListEsignSubmissionsByMarinaFiltered :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR customer_id = $3)
  AND ($4 = '' OR status = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListEsignSubmissionsByMarinaFilteredParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
	Column4        interface{}
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignSubmissionsByMarinaFiltered(ctx context.Context, arg ListEsignSubmissionsByMarinaFilteredParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByMarinaFiltered,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByStatus = `-- name: ListEsignSubmissionsByStatus :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND status = $3
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListEsignSubmissionsByStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignSubmissionsByStatus(ctx context.Context, arg ListEsignSubmissionsByStatusParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByStatus,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsFilteredByDocument = `-- name: ListEsignSubmissionsFilteredByDocument :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE document_id = $1
  AND deleted_at IS NULL
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR customer_id = $3)
  AND ($4 = '' OR LOWER(email) LIKE LOWER('%' || $4 || '%'))
  AND ($5 = '' OR LOWER(name) LIKE LOWER('%' || $5 || '%'))
ORDER BY 
  CASE 
    WHEN $6 = 'email' AND $7 = 'asc' THEN email
    WHEN $6 = 'name' AND $7 = 'asc' THEN name
    WHEN $6 = 'status' AND $7 = 'asc' THEN status
    WHEN $6 = 'customer_id' AND $7 = 'asc' THEN customer_id
  END ASC,
  CASE 
    WHEN $6 = 'email' AND $7 = 'desc' THEN email
    WHEN $6 = 'name' AND $7 = 'desc' THEN name
    WHEN $6 = 'status' AND $7 = 'desc' THEN status
    WHEN $6 = 'customer_id' AND $7 = 'desc' THEN customer_id
  END DESC,
  CASE 
    WHEN $6 = 'created_at' AND $7 = 'asc' THEN created_at
    WHEN $6 = 'updated_at' AND $7 = 'asc' THEN updated_at
  END ASC,
  CASE 
    WHEN $6 = 'created_at' AND $7 = 'desc' THEN created_at
    WHEN $6 = 'updated_at' AND $7 = 'desc' THEN updated_at
    ELSE created_at
  END DESC
LIMIT $8 OFFSET $9
`

type ListEsignSubmissionsFilteredByDocumentParams struct {
	DocumentID uuid.UUID
	Column2    interface{}
	Column3    interface{}
	Column4    interface{}
	Column5    interface{}
	Column6    interface{}
	Column7    interface{}
	Limit      int32
	Offset     int32
}

func (q *Queries) ListEsignSubmissionsFilteredByDocument(ctx context.Context, arg ListEsignSubmissionsFilteredByDocumentParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsFilteredByDocument,
		arg.DocumentID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsFilteredByStatus = `-- name: ListEsignSubmissionsFilteredByStatus :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND status = $3
  AND deleted_at IS NULL
  AND ($4 = '' OR customer_id = $4)
  AND ($5 = '' OR LOWER(email) LIKE LOWER('%' || $5 || '%'))
  AND ($6 = '' OR LOWER(name) LIKE LOWER('%' || $6 || '%'))
  AND ($7 = '' OR document_id = $7::uuid)
ORDER BY 
  CASE 
    WHEN $8 = 'email' AND $9 = 'asc' THEN email
    WHEN $8 = 'name' AND $9 = 'asc' THEN name
    WHEN $8 = 'customer_id' AND $9 = 'asc' THEN customer_id
  END ASC,
  CASE 
    WHEN $8 = 'email' AND $9 = 'desc' THEN email
    WHEN $8 = 'name' AND $9 = 'desc' THEN name
    WHEN $8 = 'customer_id' AND $9 = 'desc' THEN customer_id
  END DESC,
  CASE 
    WHEN $8 = 'created_at' AND $9 = 'asc' THEN created_at
    WHEN $8 = 'updated_at' AND $9 = 'asc' THEN updated_at
  END ASC,
  CASE 
    WHEN $8 = 'created_at' AND $9 = 'desc' THEN created_at
    WHEN $8 = 'updated_at' AND $9 = 'desc' THEN updated_at
    ELSE created_at
  END DESC
LIMIT $10 OFFSET $11
`

type ListEsignSubmissionsFilteredByStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Status         string
	Column4        interface{}
	Column5        interface{}
	Column6        interface{}
	Column7        interface{}
	Column8        interface{}
	Column9        interface{}
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignSubmissionsFilteredByStatus(ctx context.Context, arg ListEsignSubmissionsFilteredByStatusParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsFilteredByStatus,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Status,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsWithFilters = `-- name: ListEsignSubmissionsWithFilters :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR status = $3)
  AND ($4 = '' OR (
    LOWER(email) LIKE LOWER('%' || $4 || '%') OR
    LOWER(name) LIKE LOWER('%' || $4 || '%') OR
    LOWER(status) LIKE LOWER('%' || $4 || '%') OR
    LOWER(customer_id) LIKE LOWER('%' || $4 || '%')
  ))
  AND ($9 = '' OR customer_id = $9)
ORDER BY 
  CASE 
    WHEN $5 = 'email' AND $6 = 'asc' THEN email
    WHEN $5 = 'name' AND $6 = 'asc' THEN name
    WHEN $5 = 'status' AND $6 = 'asc' THEN status
    WHEN $5 = 'customer_id' AND $6 = 'asc' THEN customer_id
  END ASC,
  CASE 
    WHEN $5 = 'email' AND $6 = 'desc' THEN email
    WHEN $5 = 'name' AND $6 = 'desc' THEN name
    WHEN $5 = 'status' AND $6 = 'desc' THEN status
    WHEN $5 = 'customer_id' AND $6 = 'desc' THEN customer_id
  END DESC,
  CASE 
    WHEN $5 = 'created_at' AND $6 = 'asc' THEN created_at
    WHEN $5 = 'updated_at' AND $6 = 'asc' THEN updated_at
  END ASC,
  CASE 
    WHEN $5 = 'created_at' AND $6 = 'desc' THEN created_at
    WHEN $5 = 'updated_at' AND $6 = 'desc' THEN updated_at
    ELSE created_at
  END DESC
LIMIT $7 OFFSET $8
`

type ListEsignSubmissionsWithFiltersParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
	Column4        interface{}
	Column5        interface{}
	Column6        interface{}
	Limit          int32
	Offset         int32
	Column9        interface{}
}

func (q *Queries) ListEsignSubmissionsWithFilters(ctx context.Context, arg ListEsignSubmissionsWithFiltersParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsWithFilters,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AttachmentRequired,
			&i.ReplyTo,
			&i.CustomMessage,
			&i.IsMultipleSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEsignSubmission = `-- name: SoftDeleteEsignSubmission :exec
UPDATE esign_submissions
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteEsignSubmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEsignSubmission, id)
	return err
}

const updateEsignSubmission = `-- name: UpdateEsignSubmission :one
UPDATE esign_submissions
SET
    status = $2,
    blob_url = $3,
    blob_metadata = $4,
    customer_id = $5,
    email = $6,
    name = $7,
    attachment_required = $8,
    reply_to = $9,
    custom_message = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
`

type UpdateEsignSubmissionParams struct {
	ID                 uuid.UUID
	Status             string
	BlobUrl            string
	BlobMetadata       []byte
	CustomerID         *string
	Email              string
	Name               *string
	AttachmentRequired *bool
	ReplyTo            *string
	CustomMessage      *string
}

func (q *Queries) UpdateEsignSubmission(ctx context.Context, arg UpdateEsignSubmissionParams) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, updateEsignSubmission,
		arg.ID,
		arg.Status,
		arg.BlobUrl,
		arg.BlobMetadata,
		arg.CustomerID,
		arg.Email,
		arg.Name,
		arg.AttachmentRequired,
		arg.ReplyTo,
		arg.CustomMessage,
	)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.AttachmentRequired,
		&i.ReplyTo,
		&i.CustomMessage,
		&i.IsMultipleSignature,
	)
	return i, err
}

const updateEsignSubmissionStatus = `-- name: UpdateEsignSubmissionStatus :one
UPDATE esign_submissions
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at, name, attachment_required, reply_to, custom_message, is_multiple_signature
`

type UpdateEsignSubmissionStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateEsignSubmissionStatus(ctx context.Context, arg UpdateEsignSubmissionStatusParams) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, updateEsignSubmissionStatus, arg.ID, arg.Status)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.AttachmentRequired,
		&i.ReplyTo,
		&i.CustomMessage,
		&i.IsMultipleSignature,
	)
	return i, err
}
