// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: esign_submissions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countEsignSubmissionsByDocument = `-- name: CountEsignSubmissionsByDocument :one
SELECT COUNT(*)
FROM esign_submissions
WHERE document_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountEsignSubmissionsByDocument(ctx context.Context, documentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsByMarina = `-- name: CountEsignSubmissionsByMarina :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND deleted_at IS NULL
`

type CountEsignSubmissionsByMarinaParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
}

func (q *Queries) CountEsignSubmissionsByMarina(ctx context.Context, arg CountEsignSubmissionsByMarinaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByMarina, arg.OrganizationID, arg.MarinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsByMarinaFiltered = `-- name: CountEsignSubmissionsByMarinaFiltered :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR customer_id = $3)
  AND ($4 = '' OR status = $4)
`

type CountEsignSubmissionsByMarinaFilteredParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
	Column4        interface{}
}

func (q *Queries) CountEsignSubmissionsByMarinaFiltered(ctx context.Context, arg CountEsignSubmissionsByMarinaFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByMarinaFiltered,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignSubmissionsByStatus = `-- name: CountEsignSubmissionsByStatus :one
SELECT COUNT(*)
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND status = $3
    AND deleted_at IS NULL
`

type CountEsignSubmissionsByStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Status         string
}

func (q *Queries) CountEsignSubmissionsByStatus(ctx context.Context, arg CountEsignSubmissionsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignSubmissionsByStatus, arg.OrganizationID, arg.MarinaID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEsignSubmission = `-- name: CreateEsignSubmission :one
INSERT INTO esign_submissions (
    organization_id,
    marina_id,
    document_id,
    status,
    blob_url,
    blob_metadata,
    customer_id,
    email
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
`

type CreateEsignSubmissionParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	DocumentID     uuid.UUID
	Status         string
	BlobUrl        string
	BlobMetadata   []byte
	CustomerID     *string
	Email          string
}

func (q *Queries) CreateEsignSubmission(ctx context.Context, arg CreateEsignSubmissionParams) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, createEsignSubmission,
		arg.OrganizationID,
		arg.MarinaID,
		arg.DocumentID,
		arg.Status,
		arg.BlobUrl,
		arg.BlobMetadata,
		arg.CustomerID,
		arg.Email,
	)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEsignSubmissionByID = `-- name: GetEsignSubmissionByID :one
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
FROM esign_submissions
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetEsignSubmissionByID(ctx context.Context, id uuid.UUID) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, getEsignSubmissionByID, id)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteEsignSubmission = `-- name: HardDeleteEsignSubmission :exec
DELETE FROM esign_submissions
WHERE id = $1
`

func (q *Queries) HardDeleteEsignSubmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteEsignSubmission, id)
	return err
}

const listEsignSubmissionsByCustomerID = `-- name: ListEsignSubmissionsByCustomerID :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
FROM esign_submissions
WHERE customer_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEsignSubmissionsByCustomerIDParams struct {
	CustomerID *string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListEsignSubmissionsByCustomerID(ctx context.Context, arg ListEsignSubmissionsByCustomerIDParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByCustomerID, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByDocument = `-- name: ListEsignSubmissionsByDocument :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
FROM esign_submissions
WHERE document_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEsignSubmissionsByDocumentParams struct {
	DocumentID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListEsignSubmissionsByDocument(ctx context.Context, arg ListEsignSubmissionsByDocumentParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByDocument, arg.DocumentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByMarina = `-- name: ListEsignSubmissionsByMarina :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListEsignSubmissionsByMarinaParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignSubmissionsByMarina(ctx context.Context, arg ListEsignSubmissionsByMarinaParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByMarina,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByMarinaFiltered = `-- name: ListEsignSubmissionsByMarinaFiltered :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
FROM esign_submissions
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR customer_id = $3)
  AND ($4 = '' OR status = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListEsignSubmissionsByMarinaFilteredParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
	Column4        interface{}
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignSubmissionsByMarinaFiltered(ctx context.Context, arg ListEsignSubmissionsByMarinaFilteredParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByMarinaFiltered,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignSubmissionsByStatus = `-- name: ListEsignSubmissionsByStatus :many
SELECT id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
FROM esign_submissions
WHERE organization_id = $1
    AND marina_id = $2
    AND status = $3
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListEsignSubmissionsByStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignSubmissionsByStatus(ctx context.Context, arg ListEsignSubmissionsByStatusParams) ([]EsignSubmission, error) {
	rows, err := q.db.Query(ctx, listEsignSubmissionsByStatus,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignSubmission
	for rows.Next() {
		var i EsignSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.DocumentID,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CustomerID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEsignSubmission = `-- name: SoftDeleteEsignSubmission :exec
UPDATE esign_submissions
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteEsignSubmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEsignSubmission, id)
	return err
}

const updateEsignSubmission = `-- name: UpdateEsignSubmission :one
UPDATE esign_submissions
SET
    status = $2,
    blob_url = $3,
    blob_metadata = $4,
    customer_id = $5,
    email = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
`

type UpdateEsignSubmissionParams struct {
	ID           uuid.UUID
	Status       string
	BlobUrl      string
	BlobMetadata []byte
	CustomerID   *string
	Email        string
}

func (q *Queries) UpdateEsignSubmission(ctx context.Context, arg UpdateEsignSubmissionParams) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, updateEsignSubmission,
		arg.ID,
		arg.Status,
		arg.BlobUrl,
		arg.BlobMetadata,
		arg.CustomerID,
		arg.Email,
	)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEsignSubmissionStatus = `-- name: UpdateEsignSubmissionStatus :one
UPDATE esign_submissions
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, organization_id, marina_id, document_id, status, blob_url, blob_metadata, customer_id, email, created_at, updated_at, deleted_at
`

type UpdateEsignSubmissionStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateEsignSubmissionStatus(ctx context.Context, arg UpdateEsignSubmissionStatusParams) (EsignSubmission, error) {
	row := q.db.QueryRow(ctx, updateEsignSubmissionStatus, arg.ID, arg.Status)
	var i EsignSubmission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.DocumentID,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CustomerID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
