// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: esign_templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countEsignTemplatesByMarina = `-- name: CountEsignTemplatesByMarina :one
SELECT COUNT(*)
FROM esign_templates
WHERE organization_id = $1
    AND marina_id = $2
    AND deleted_at IS NULL
`

type CountEsignTemplatesByMarinaParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
}

func (q *Queries) CountEsignTemplatesByMarina(ctx context.Context, arg CountEsignTemplatesByMarinaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignTemplatesByMarina, arg.OrganizationID, arg.MarinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEsignTemplatesByMarinaStatus = `-- name: CountEsignTemplatesByMarinaStatus :one
SELECT COUNT(*)
FROM esign_templates
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR status = $3)
`

type CountEsignTemplatesByMarinaStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
}

func (q *Queries) CountEsignTemplatesByMarinaStatus(ctx context.Context, arg CountEsignTemplatesByMarinaStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEsignTemplatesByMarinaStatus, arg.OrganizationID, arg.MarinaID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEsignTemplate = `-- name: CreateEsignTemplate :one
INSERT INTO esign_templates (
    organization_id,
    marina_id,
    name,
    description,
    type,
    status,
    blob_url,
    blob_metadata,
    json_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, organization_id, marina_id, name, description, type, status, blob_url, blob_metadata, created_at, updated_at, deleted_at, json_data
`

type CreateEsignTemplateParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Name           string
	Description    *string
	Type           string
	Status         string
	BlobUrl        string
	BlobMetadata   []byte
	JsonData       []byte
}

func (q *Queries) CreateEsignTemplate(ctx context.Context, arg CreateEsignTemplateParams) (EsignTemplate, error) {
	row := q.db.QueryRow(ctx, createEsignTemplate,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.BlobUrl,
		arg.BlobMetadata,
		arg.JsonData,
	)
	var i EsignTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.JsonData,
	)
	return i, err
}

const getEsignTemplateByID = `-- name: GetEsignTemplateByID :one
SELECT id, organization_id, marina_id, name, description, type, status, blob_url, blob_metadata, created_at, updated_at, deleted_at, json_data
FROM esign_templates
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetEsignTemplateByID(ctx context.Context, id uuid.UUID) (EsignTemplate, error) {
	row := q.db.QueryRow(ctx, getEsignTemplateByID, id)
	var i EsignTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.JsonData,
	)
	return i, err
}

const hardDeleteEsignTemplate = `-- name: HardDeleteEsignTemplate :exec
DELETE FROM esign_templates
WHERE id = $1
`

func (q *Queries) HardDeleteEsignTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteEsignTemplate, id)
	return err
}

const listEsignTemplatesByMarina = `-- name: ListEsignTemplatesByMarina :many
SELECT id, organization_id, marina_id, name, description, type, status, blob_url, blob_metadata, created_at, updated_at, deleted_at, json_data
FROM esign_templates
WHERE organization_id = $1
    AND marina_id = $2
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListEsignTemplatesByMarinaParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignTemplatesByMarina(ctx context.Context, arg ListEsignTemplatesByMarinaParams) ([]EsignTemplate, error) {
	rows, err := q.db.Query(ctx, listEsignTemplatesByMarina,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignTemplate
	for rows.Next() {
		var i EsignTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.JsonData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEsignTemplatesByMarinaStatus = `-- name: ListEsignTemplatesByMarinaStatus :many
SELECT id, organization_id, marina_id, name, description, type, status, blob_url, blob_metadata, created_at, updated_at, deleted_at, json_data
FROM esign_templates
WHERE organization_id = $1
  AND marina_id = $2
  AND deleted_at IS NULL
  AND ($3 = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListEsignTemplatesByMarinaStatusParams struct {
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Column3        interface{}
	Limit          int32
	Offset         int32
}

func (q *Queries) ListEsignTemplatesByMarinaStatus(ctx context.Context, arg ListEsignTemplatesByMarinaStatusParams) ([]EsignTemplate, error) {
	rows, err := q.db.Query(ctx, listEsignTemplatesByMarinaStatus,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsignTemplate
	for rows.Next() {
		var i EsignTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.BlobUrl,
			&i.BlobMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.JsonData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEsignTemplate = `-- name: SoftDeleteEsignTemplate :exec
UPDATE esign_templates
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteEsignTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEsignTemplate, id)
	return err
}

const updateEsignTemplate = `-- name: UpdateEsignTemplate :one
UPDATE esign_templates
SET
    name = $2,
    description = $3,
    type = $4,
    status = $5,
    blob_url = $6,
    blob_metadata = $7,
    json_data = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, organization_id, marina_id, name, description, type, status, blob_url, blob_metadata, created_at, updated_at, deleted_at, json_data
`

type UpdateEsignTemplateParams struct {
	ID           uuid.UUID
	Name         string
	Description  *string
	Type         string
	Status       string
	BlobUrl      string
	BlobMetadata []byte
	JsonData     []byte
}

func (q *Queries) UpdateEsignTemplate(ctx context.Context, arg UpdateEsignTemplateParams) (EsignTemplate, error) {
	row := q.db.QueryRow(ctx, updateEsignTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.BlobUrl,
		arg.BlobMetadata,
		arg.JsonData,
	)
	var i EsignTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.JsonData,
	)
	return i, err
}

const updateEsignTemplateStatus = `-- name: UpdateEsignTemplateStatus :one
UPDATE esign_templates
SET
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, organization_id, marina_id, name, description, type, status, blob_url, blob_metadata, created_at, updated_at, deleted_at, json_data
`

type UpdateEsignTemplateStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateEsignTemplateStatus(ctx context.Context, arg UpdateEsignTemplateStatusParams) (EsignTemplate, error) {
	row := q.db.QueryRow(ctx, updateEsignTemplateStatus, arg.ID, arg.Status)
	var i EsignTemplate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.BlobUrl,
		&i.BlobMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.JsonData,
	)
	return i, err
}
