// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invite.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (
    user_id,
    email,
    token,
    expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, email, token, expires_at, used, created_at
`

type CreateInviteParams struct {
	UserID    uuid.UUID
	Email     string
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.UserID,
		arg.Email,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const expireInvitesByEmail = `-- name: ExpireInvitesByEmail :exec
UPDATE invites
SET expires_at = CURRENT_TIMESTAMP
WHERE email = $1 AND used = FALSE
`

func (q *Queries) ExpireInvitesByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, expireInvitesByEmail, email)
	return err
}

const expireInvitesByUserID = `-- name: ExpireInvitesByUserID :exec
UPDATE invites
SET expires_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND used = FALSE
`

func (q *Queries) ExpireInvitesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireInvitesByUserID, userID)
	return err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, user_id, email, token, expires_at, used, created_at FROM invites
WHERE token = $1 AND used = FALSE AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByUserID = `-- name: GetInviteByUserID :one
SELECT id, user_id, email, token, expires_at, used, created_at FROM invites
WHERE user_id = $1 AND used = FALSE AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetInviteByUserID(ctx context.Context, userID uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByUserID, userID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitesByEmail = `-- name: GetInvitesByEmail :many
SELECT id, user_id, email, token, expires_at, used, created_at FROM invites
WHERE email = $1 AND used = FALSE AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

func (q *Queries) GetInvitesByEmail(ctx context.Context, email string) ([]Invite, error) {
	rows, err := q.db.Query(ctx, getInvitesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Token,
			&i.ExpiresAt,
			&i.Used,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAsUsed = `-- name: MarkInviteAsUsed :one
UPDATE invites
SET used = TRUE
WHERE token = $1 AND used = FALSE AND expires_at > CURRENT_TIMESTAMP
RETURNING id, user_id, email, token, expires_at, used, created_at
`

func (q *Queries) MarkInviteAsUsed(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, markInviteAsUsed, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}
