// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: marina_usage_history.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMarinaUsageHistory = `-- name: CreateMarinaUsageHistory :one
INSERT INTO marina_usage_history (
    marina_id,
    storage_usage,
    email_usage,
    text_usage,
    document_usage
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, marina_id, storage_usage, email_usage, text_usage, created_at, updated_at, month_date, document_usage
`

type CreateMarinaUsageHistoryParams struct {
	MarinaID      uuid.UUID
	StorageUsage  int64
	EmailUsage    int16
	TextUsage     int16
	DocumentUsage *int64
}

func (q *Queries) CreateMarinaUsageHistory(ctx context.Context, arg CreateMarinaUsageHistoryParams) (MarinaUsageHistory, error) {
	row := q.db.QueryRow(ctx, createMarinaUsageHistory,
		arg.MarinaID,
		arg.StorageUsage,
		arg.EmailUsage,
		arg.TextUsage,
		arg.DocumentUsage,
	)
	var i MarinaUsageHistory
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.StorageUsage,
		&i.EmailUsage,
		&i.TextUsage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MonthDate,
		&i.DocumentUsage,
	)
	return i, err
}

const deleteMarinaUsageHistory = `-- name: DeleteMarinaUsageHistory :exec
DELETE FROM marina_usage_history
WHERE id = $1
`

func (q *Queries) DeleteMarinaUsageHistory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMarinaUsageHistory, id)
	return err
}

const getLatestMarinaUsageHistory = `-- name: GetLatestMarinaUsageHistory :one
SELECT id, marina_id, storage_usage, email_usage, text_usage, created_at, updated_at, month_date, document_usage FROM marina_usage_history
WHERE marina_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMarinaUsageHistory(ctx context.Context, marinaID uuid.UUID) (MarinaUsageHistory, error) {
	row := q.db.QueryRow(ctx, getLatestMarinaUsageHistory, marinaID)
	var i MarinaUsageHistory
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.StorageUsage,
		&i.EmailUsage,
		&i.TextUsage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MonthDate,
		&i.DocumentUsage,
	)
	return i, err
}

const getMarinaUsageHistoryByDateRange = `-- name: GetMarinaUsageHistoryByDateRange :many
SELECT id, marina_id, storage_usage, email_usage, text_usage, created_at, updated_at, month_date, document_usage FROM marina_usage_history
WHERE marina_id = $1
AND created_at >= $2
AND created_at <= $3
ORDER BY created_at DESC
`

type GetMarinaUsageHistoryByDateRangeParams struct {
	MarinaID    uuid.UUID
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) GetMarinaUsageHistoryByDateRange(ctx context.Context, arg GetMarinaUsageHistoryByDateRangeParams) ([]MarinaUsageHistory, error) {
	rows, err := q.db.Query(ctx, getMarinaUsageHistoryByDateRange, arg.MarinaID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarinaUsageHistory
	for rows.Next() {
		var i MarinaUsageHistory
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.StorageUsage,
			&i.EmailUsage,
			&i.TextUsage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MonthDate,
			&i.DocumentUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaUsageHistoryByID = `-- name: GetMarinaUsageHistoryByID :one
SELECT id, marina_id, storage_usage, email_usage, text_usage, created_at, updated_at, month_date, document_usage FROM marina_usage_history
WHERE id = $1
`

func (q *Queries) GetMarinaUsageHistoryByID(ctx context.Context, id uuid.UUID) (MarinaUsageHistory, error) {
	row := q.db.QueryRow(ctx, getMarinaUsageHistoryByID, id)
	var i MarinaUsageHistory
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.StorageUsage,
		&i.EmailUsage,
		&i.TextUsage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MonthDate,
		&i.DocumentUsage,
	)
	return i, err
}

const getMarinaUsageHistoryByMarinaID = `-- name: GetMarinaUsageHistoryByMarinaID :many
SELECT id, marina_id, storage_usage, email_usage, text_usage, created_at, updated_at, month_date, document_usage FROM marina_usage_history
WHERE marina_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMarinaUsageHistoryByMarinaID(ctx context.Context, marinaID uuid.UUID) ([]MarinaUsageHistory, error) {
	rows, err := q.db.Query(ctx, getMarinaUsageHistoryByMarinaID, marinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarinaUsageHistory
	for rows.Next() {
		var i MarinaUsageHistory
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.StorageUsage,
			&i.EmailUsage,
			&i.TextUsage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MonthDate,
			&i.DocumentUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaUsageHistoryByMonth = `-- name: GetMarinaUsageHistoryByMonth :one
SELECT id, marina_id, storage_usage, email_usage, text_usage, created_at, updated_at, month_date, document_usage FROM marina_usage_history
WHERE marina_id = $1
AND DATE_TRUNC('month', created_at) = DATE_TRUNC('month', $2::timestamp)
ORDER BY created_at DESC
LIMIT 1
`

type GetMarinaUsageHistoryByMonthParams struct {
	MarinaID uuid.UUID
	Column2  pgtype.Timestamp
}

func (q *Queries) GetMarinaUsageHistoryByMonth(ctx context.Context, arg GetMarinaUsageHistoryByMonthParams) (MarinaUsageHistory, error) {
	row := q.db.QueryRow(ctx, getMarinaUsageHistoryByMonth, arg.MarinaID, arg.Column2)
	var i MarinaUsageHistory
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.StorageUsage,
		&i.EmailUsage,
		&i.TextUsage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MonthDate,
		&i.DocumentUsage,
	)
	return i, err
}

const updateMarinaUsageHistory = `-- name: UpdateMarinaUsageHistory :one
UPDATE marina_usage_history
SET
    storage_usage = $2,
    email_usage = $3,
    text_usage = $4,
    document_usage = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, marina_id, storage_usage, email_usage, text_usage, created_at, updated_at, month_date, document_usage
`

type UpdateMarinaUsageHistoryParams struct {
	ID            uuid.UUID
	StorageUsage  int64
	EmailUsage    int16
	TextUsage     int16
	DocumentUsage *int64
}

func (q *Queries) UpdateMarinaUsageHistory(ctx context.Context, arg UpdateMarinaUsageHistoryParams) (MarinaUsageHistory, error) {
	row := q.db.QueryRow(ctx, updateMarinaUsageHistory,
		arg.ID,
		arg.StorageUsage,
		arg.EmailUsage,
		arg.TextUsage,
		arg.DocumentUsage,
	)
	var i MarinaUsageHistory
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.StorageUsage,
		&i.EmailUsage,
		&i.TextUsage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MonthDate,
		&i.DocumentUsage,
	)
	return i, err
}
