// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    marina_id,
    customer_id,
    type,
    direction,
    body,
    sender,
    recipient,
    contact,
    status,
    pinned
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, marina_id, customer_id, type, direction, body, sender, recipient, contact, status, pinned, created_at, updated_at, deleted_at
`

type CreateMessageParams struct {
	MarinaID   uuid.UUID
	CustomerID string
	Type       string
	Direction  string
	Body       string
	Sender     string
	Recipient  string
	Contact    string
	Status     string
	Pinned     bool
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.MarinaID,
		arg.CustomerID,
		arg.Type,
		arg.Direction,
		arg.Body,
		arg.Sender,
		arg.Recipient,
		arg.Contact,
		arg.Status,
		arg.Pinned,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.CustomerID,
		&i.Type,
		&i.Direction,
		&i.Body,
		&i.Sender,
		&i.Recipient,
		&i.Contact,
		&i.Status,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE messages
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
AND marina_id = $2
AND customer_id = $3
`

type DeleteMessageParams struct {
	ID         uuid.UUID
	MarinaID   uuid.UUID
	CustomerID string
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.MarinaID, arg.CustomerID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, marina_id, customer_id, type, direction, body, sender, recipient, contact, status, pinned, created_at, updated_at, deleted_at
FROM messages
WHERE id = $1
AND marina_id = $2
AND customer_id = $3
AND deleted_at IS NULL
`

type GetMessageByIDParams struct {
	ID         uuid.UUID
	MarinaID   uuid.UUID
	CustomerID string
}

func (q *Queries) GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, arg.ID, arg.MarinaID, arg.CustomerID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.CustomerID,
		&i.Type,
		&i.Direction,
		&i.Body,
		&i.Sender,
		&i.Recipient,
		&i.Contact,
		&i.Status,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, marina_id, customer_id, type, direction, body, sender, recipient, contact, status, pinned, created_at, updated_at, deleted_at
FROM messages
WHERE marina_id = $1
AND customer_id = $2
AND deleted_at IS NULL
ORDER BY pinned DESC, created_at DESC
LIMIT $3
OFFSET $4
`

type ListMessagesParams struct {
	MarinaID   uuid.UUID
	CustomerID string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.MarinaID,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.CustomerID,
			&i.Type,
			&i.Direction,
			&i.Body,
			&i.Sender,
			&i.Recipient,
			&i.Contact,
			&i.Status,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAll = `-- name: ListMessagesAll :many
SELECT id, marina_id, customer_id, type, direction, body, sender, recipient, contact, status, pinned, created_at, updated_at, deleted_at
FROM messages
WHERE marina_id = $1
AND customer_id = $2
AND deleted_at IS NULL
ORDER BY pinned DESC, created_at DESC
`

type ListMessagesAllParams struct {
	MarinaID   uuid.UUID
	CustomerID string
}

func (q *Queries) ListMessagesAll(ctx context.Context, arg ListMessagesAllParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesAll, arg.MarinaID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.CustomerID,
			&i.Type,
			&i.Direction,
			&i.Body,
			&i.Sender,
			&i.Recipient,
			&i.Contact,
			&i.Status,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByCustomer = `-- name: ListMessagesByCustomer :many
SELECT id, marina_id, customer_id, type, direction, body, sender, recipient, contact, status, pinned, created_at, updated_at, deleted_at
FROM messages
WHERE marina_id = $1
AND customer_id = $2
AND type IN ('email', 'sms')
AND deleted_at IS NULL
ORDER BY pinned DESC, created_at DESC
LIMIT $3
OFFSET $4
`

type ListMessagesByCustomerParams struct {
	MarinaID   uuid.UUID
	CustomerID string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListMessagesByCustomer(ctx context.Context, arg ListMessagesByCustomerParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByCustomer,
		arg.MarinaID,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.CustomerID,
			&i.Type,
			&i.Direction,
			&i.Body,
			&i.Sender,
			&i.Recipient,
			&i.Contact,
			&i.Status,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByCustomerAll = `-- name: ListMessagesByCustomerAll :many
SELECT id, marina_id, customer_id, type, direction, body, sender, recipient, contact, status, pinned, created_at, updated_at, deleted_at
FROM messages
WHERE marina_id = $1
AND customer_id = $2
AND type IN ('email', 'sms')
AND deleted_at IS NULL
ORDER BY pinned DESC, created_at DESC
`

type ListMessagesByCustomerAllParams struct {
	MarinaID   uuid.UUID
	CustomerID string
}

func (q *Queries) ListMessagesByCustomerAll(ctx context.Context, arg ListMessagesByCustomerAllParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByCustomerAll, arg.MarinaID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.CustomerID,
			&i.Type,
			&i.Direction,
			&i.Body,
			&i.Sender,
			&i.Recipient,
			&i.Contact,
			&i.Status,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE messages
SET status = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateMessageStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatus, arg.Status, arg.ID)
	return err
}
