// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         uuid.UUID
	Street     *string
	City       *string
	State      *string
	PostalCode *string
	Country    *string
	Latitude   pgtype.Numeric
	Longitude  pgtype.Numeric
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type Marina struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Email          string
	Location       *string
	Phone          *string
	Country        *string
	Currency       *string
	WorkingHours   []byte
	Website        *string
	Image          *string
	MaxUsers       *int32
	IsActive       *bool
	IsTest         *bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	AddressID      uuid.UUID
}

type Organization struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Image     *string
	Website   *string
	Country   *string
	Phone     *string
	IsActive  *bool
	IsTest    *bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	AddressID uuid.UUID
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Permissions []byte
	IsActive    *bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type User struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
}

type UserMarina struct {
	UserID     uuid.UUID
	MarinaID   uuid.UUID
	AssignedAt pgtype.Timestamp
}
