// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         uuid.UUID
	Street     *string
	City       *string
	State      *string
	PostalCode *string
	Country    *string
	Latitude   float64
	Longitude  float64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type BatchPayment struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	LocationCode   string
	BatchID        string
	PostBatch      bool
	TotalAmount    pgtype.Numeric
	ReceiptCount   int32
	Status         string
	PostResult     *string
	ReferenceIds   []string
	SubmittedBy    string
	SubmittedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type BatchPaymentReceipt struct {
	ID             uuid.UUID
	BatchPaymentID uuid.UUID
	CustomerID     string
	InvoiceID      string
	Amount         pgtype.Numeric
	PaymentMethod  string
	Reference      string
	Description    *string
	PaymentDate    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Contact struct {
	ID          uuid.UUID
	MarinaID    uuid.UUID
	Type        string
	Name        string
	Description *string
	Email       *string
	Phone       *string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	IsCpContact *bool
}

type Criterium struct {
	ID          uuid.UUID
	MarinaID    uuid.UUID
	Name        string
	Description *string
	Criteria    []byte
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type CustomerSetting struct {
	ID           uuid.UUID
	MarinaID     uuid.UUID
	CustomerID   string
	EnablePortal *bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type DmeAttachmentMetadatum struct {
	ID     uuid.UUID
	S3Path string
	Public bool
}

type DmeCredential struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Username       string
	Password       *string
	IsOldApi       *bool
	AccessToken    *string
	RefreshToken   *string
	ExpiryDate     pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type DmeSysid struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Name           string
	Description    *string
	SystemID       string
	IsActive       *bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type Document struct {
	ID         uuid.UUID
	MarinaID   uuid.UUID
	EntityType string
	EntityID   string
	FileName   string
	FileType   string
	FilePath   string
	FileSize   int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	Public     bool
}

type DocumentPlan struct {
	ID            uuid.UUID
	Name          string
	MonthlyPrice  float64
	DocumentLimit *int32
	UserLimit     *string
	IsMostPopular *bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type EsignDocument struct {
	ID             uuid.UUID
	TemplateID     uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Type           string
	Status         string
	BlobUrl        string
	BlobMetadata   []byte
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type EsignSubmission struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	DocumentID          uuid.UUID
	Status              string
	BlobUrl             string
	BlobMetadata        []byte
	CustomerID          *string
	Email               string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	Name                *string
	AttachmentRequired  *bool
	ReplyTo             *string
	CustomMessage       *string
	IsMultipleSignature bool
	CustomerName        *string
	ReplyName           *string
}

type EsignSubmissionSigner struct {
	ID             uuid.UUID
	SubmissionID   uuid.UUID
	Email          string
	Name           *string
	SignOrder      int32
	Status         string
	SignedAt       pgtype.Timestamp
	DeclinedAt     pgtype.Timestamp
	DeclinedReason *string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type EsignTemplate struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Name           string
	Description    *string
	Type           string
	Status         string
	BlobUrl        string
	BlobMetadata   []byte
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	JsonData       []byte
}

type Invite struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	Token     string
	ExpiresAt pgtype.Timestamp
	Used      *bool
	CreatedAt pgtype.Timestamp
}

type Marina struct {
	ID                    uuid.UUID
	OrganizationID        uuid.UUID
	Name                  string
	Email                 string
	Location              *string
	Phone                 *string
	Country               *string
	Currency              *string
	WorkingHours          []byte
	Website               *string
	Image                 *string
	MaxUsers              *int32
	IsActive              *bool
	IsTest                *bool
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
	DeletedAt             pgtype.Timestamp
	AddressID             uuid.UUID
	SystemID              *string
	StorageUsage          *int64
	EmailUsage            *int16
	TextUsage             *int16
	NotesMessagesPlanID   uuid.UUID
	StoragePlanID         uuid.UUID
	Modules               []byte
	InternalAnnouncement  *string
	ExternalAnnouncement  *string
	DocumentPlanID        uuid.UUID
	DocumentUsage         *int64
	AiFormDetectionUsage  *int16
	AiComposeMessageUsage *int16
}

type MarinaGallery struct {
	ID          uuid.UUID
	MarinaID    uuid.UUID
	ImageUrl    string
	Description *string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	Public      bool
}

type MarinaUsageHistory struct {
	ID                    uuid.UUID
	MarinaID              uuid.UUID
	StorageUsage          int64
	EmailUsage            int16
	TextUsage             int16
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	MonthDate             pgtype.Date
	DocumentUsage         *int64
	AiFormDetectionUsage  *int16
	AiComposeMessageUsage *int16
}

type Message struct {
	ID         uuid.UUID
	MarinaID   uuid.UUID
	CustomerID string
	Type       string
	Direction  string
	Body       string
	Sender     string
	Recipient  string
	Contact    string
	Status     string
	Pinned     bool
	Subject    pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type NotesMessagesPlan struct {
	ID            uuid.UUID
	Name          string
	MonthlyPrice  float64
	TextLimit     *int32
	EmailLimit    *string
	UserLimit     *string
	IsMostPopular *bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Notification struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Type           string
	Title          string
	Content        string
	Data           []byte
	Read           *bool
	ReadAt         pgtype.Timestamp
	Priority       *string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type NotificationPreference struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	NotificationType string
	Enabled          *bool
	DeliveryMethod   *string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Organization struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Image     *string
	Website   *string
	Country   *string
	Phone     *string
	IsActive  *bool
	IsTest    *bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	AddressID uuid.UUID
}

type PasswordHistory struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}

type PasswordRecovery struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	Token     string
	ExpiresAt pgtype.Timestamp
	Used      *bool
	CreatedAt pgtype.Timestamp
}

type Payment struct {
	ID                   uuid.UUID
	MarinaID             uuid.UUID
	OrganizationID       uuid.UUID
	EntityType           *string
	EntityID             *string
	Amount               pgtype.Numeric
	Currency             string
	PaymentMethod        *string
	ReferenceNumber      string
	Status               string
	AuthorizationStatus  *string
	BatchStatus          *string
	AdyenPspReference    *string
	AdyenSessionID       *string
	BatchID              *string
	BatchPaymentID       uuid.UUID
	PaymentDate          pgtype.Timestamptz
	AuthorizedAt         pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	FailedAt             pgtype.Timestamptz
	CustomerID           *string
	LocationCode         *string
	TransactionID        *string
	AuthCode             *string
	AdyenWebhookPayload  *string
	DmeBatchRequest      *string
	DmeBatchResponse     *string
	ErrorMessage         *string
	ErrorCode            *string
	InternalNotes        *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	AdyenPaymentResponse *string
	AdyenPaymentPayload  *string
}

type PaymentLink struct {
	ID             uuid.UUID
	Token          string
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	CustomerID     string
	Scope          string
	ExpiresAt      pgtype.Timestamptz
	Used           bool
	Revoked        bool
	CreatedAt      pgtype.Timestamptz
	UsedAt         pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type Role struct {
	ID             uuid.UUID
	Name           string
	Description    *string
	Permissions    []byte
	IsActive       *bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	IsCustomerRole *bool
	Type           string
	MarinaID       uuid.UUID
}

type StoragePlan struct {
	ID             uuid.UUID
	Name           string
	MonthlyPrice   float64
	StorageLimitGb *int32
	UserLimit      *string
	IsMostPopular  *bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type TaxConfiguration struct {
	ID                        uuid.UUID
	MarinaID                  uuid.UUID
	ConvenienceFee            pgtype.Numeric
	ConvenienceFeeType        string
	ConvenienceFeeEnabled     bool
	ConvenienceFeeDescription *string
	Surcharge                 pgtype.Numeric
	SurchargeType             string
	SurchargeEnabled          bool
	SurchargeDescription      *string
	PaymentType               string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type User struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
}

type UserMarina struct {
	UserID     uuid.UUID
	MarinaID   uuid.UUID
	AssignedAt pgtype.Timestamp
	CustomerID *string
	RoleID     uuid.UUID
}

type VesselGallery struct {
	ID          uuid.UUID
	MarinaID    uuid.UUID
	CustomerID  string
	VesselID    string
	ImageUrl    string
	Description *string
	Main        *bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	Public      bool
}
