// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         uuid.UUID
	Street     *string
	City       *string
	State      *string
	PostalCode *string
	Country    *string
	Latitude   float64
	Longitude  float64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type Contact struct {
	ID          uuid.UUID
	MarinaID    uuid.UUID
	Type        string
	Name        string
	Description *string
	Email       *string
	Phone       *string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
	IsCpContact *bool
}

type CustomerSetting struct {
	ID           uuid.UUID
	MarinaID     uuid.UUID
	CustomerID   string
	EnablePortal *bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type DmeCredential struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Username       string
	Password       *string
	IsOldApi       *bool
	AccessToken    *string
	RefreshToken   *string
	ExpiryDate     pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type DmeSysid struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Name           string
	Description    *string
	SystemID       string
	IsActive       *bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
}

type Document struct {
	ID         uuid.UUID
	MarinaID   uuid.UUID
	EntityType string
	EntityID   string
	FileName   string
	FileType   string
	FilePath   string
	FileSize   int64
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Invite struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	Token     string
	ExpiresAt pgtype.Timestamp
	Used      *bool
	CreatedAt pgtype.Timestamp
}

type Marina struct {
	ID                  uuid.UUID
	OrganizationID      uuid.UUID
	Name                string
	Email               string
	Location            *string
	Phone               *string
	Country             *string
	Currency            *string
	WorkingHours        []byte
	Website             *string
	Image               *string
	MaxUsers            *int32
	IsActive            *bool
	IsTest              *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	AddressID           uuid.UUID
	SystemID            *string
	StorageUsage        *int64
	EmailUsage          *int16
	TextUsage           *int16
	NotesMessagesPlanID uuid.UUID
	StoragePlanID       uuid.UUID
	Modules             []byte
}

type MarinaGallery struct {
	ID          uuid.UUID
	MarinaID    uuid.UUID
	ImageUrl    string
	Description *string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type MarinaUsageHistory struct {
	ID           uuid.UUID
	MarinaID     uuid.UUID
	StorageUsage int64
	EmailUsage   int16
	TextUsage    int16
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	MonthDate    pgtype.Date
}

type Message struct {
	ID         uuid.UUID
	MarinaID   uuid.UUID
	CustomerID string
	Type       string
	Direction  string
	Body       string
	Sender     string
	Recipient  string
	Contact    string
	Status     string
	Pinned     bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type NotesMessagesPlan struct {
	ID            uuid.UUID
	Name          string
	MonthlyPrice  float64
	TextLimit     *int32
	EmailLimit    *string
	UserLimit     *string
	IsMostPopular *bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Notification struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Type           string
	Title          string
	Content        string
	Data           []byte
	Read           *bool
	ReadAt         pgtype.Timestamp
	Priority       *string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type NotificationPreference struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	NotificationType string
	Enabled          *bool
	DeliveryMethod   *string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Organization struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Image     *string
	Website   *string
	Country   *string
	Phone     *string
	IsActive  *bool
	IsTest    *bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	AddressID uuid.UUID
}

type PasswordHistory struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}

type PasswordRecovery struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	Token     string
	ExpiresAt pgtype.Timestamp
	Used      *bool
	CreatedAt pgtype.Timestamp
}

type Role struct {
	ID             uuid.UUID
	Name           string
	Description    *string
	Permissions    []byte
	IsActive       *bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	IsCustomerRole *bool
	Type           string
}

type StoragePlan struct {
	ID             uuid.UUID
	Name           string
	MonthlyPrice   float64
	StorageLimitGb *int32
	UserLimit      *string
	IsMostPopular  *bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type User struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
}

type UserMarina struct {
	UserID     uuid.UUID
	MarinaID   uuid.UUID
	AssignedAt pgtype.Timestamp
	CustomerID *string
}

type VesselGallery struct {
	ID          uuid.UUID
	MarinaID    uuid.UUID
	CustomerID  string
	VesselID    string
	ImageUrl    string
	Description *string
	Main        *bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}
