// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notes_messages_plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createNotesMessagesPlan = `-- name: CreateNotesMessagesPlan :one
INSERT INTO notes_messages_plans (
    name,
    monthly_price,
    text_limit,
    email_limit,
    user_limit,
    is_most_popular
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at
`

type CreateNotesMessagesPlanParams struct {
	Name          string
	MonthlyPrice  float64
	TextLimit     *string
	EmailLimit    *string
	UserLimit     *string
	IsMostPopular *bool
}

// Create a new notes and messages plan
func (q *Queries) CreateNotesMessagesPlan(ctx context.Context, arg CreateNotesMessagesPlanParams) (NotesMessagesPlan, error) {
	row := q.db.QueryRow(ctx, createNotesMessagesPlan,
		arg.Name,
		arg.MonthlyPrice,
		arg.TextLimit,
		arg.EmailLimit,
		arg.UserLimit,
		arg.IsMostPopular,
	)
	var i NotesMessagesPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TextLimit,
		&i.EmailLimit,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarinaNotesMessagesPlan = `-- name: GetMarinaNotesMessagesPlan :one
SELECT nmp.id, nmp.name, nmp.monthly_price, nmp.text_limit, nmp.email_limit, nmp.user_limit, nmp.is_most_popular, nmp.created_at, nmp.updated_at 
FROM notes_messages_plans nmp
JOIN marinas m ON m.notes_messages_plan_id = nmp.id
WHERE m.id = $1
`

// Get marina's current plan
func (q *Queries) GetMarinaNotesMessagesPlan(ctx context.Context, id uuid.UUID) (NotesMessagesPlan, error) {
	row := q.db.QueryRow(ctx, getMarinaNotesMessagesPlan, id)
	var i NotesMessagesPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TextLimit,
		&i.EmailLimit,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMostPopularNotesMessagesPlan = `-- name: GetMostPopularNotesMessagesPlan :one
SELECT id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at FROM notes_messages_plans WHERE is_most_popular = true LIMIT 1
`

// Get the most popular plan
func (q *Queries) GetMostPopularNotesMessagesPlan(ctx context.Context) (NotesMessagesPlan, error) {
	row := q.db.QueryRow(ctx, getMostPopularNotesMessagesPlan)
	var i NotesMessagesPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TextLimit,
		&i.EmailLimit,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesMessagesPlanByID = `-- name: GetNotesMessagesPlanByID :one
SELECT id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at FROM notes_messages_plans WHERE id = $1
`

// Get a specific plan by ID
func (q *Queries) GetNotesMessagesPlanByID(ctx context.Context, id uuid.UUID) (NotesMessagesPlan, error) {
	row := q.db.QueryRow(ctx, getNotesMessagesPlanByID, id)
	var i NotesMessagesPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TextLimit,
		&i.EmailLimit,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesMessagesPlanByName = `-- name: GetNotesMessagesPlanByName :one
SELECT id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at FROM notes_messages_plans WHERE name = $1
`

// Get plan by name
func (q *Queries) GetNotesMessagesPlanByName(ctx context.Context, name string) (NotesMessagesPlan, error) {
	row := q.db.QueryRow(ctx, getNotesMessagesPlanByName, name)
	var i NotesMessagesPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TextLimit,
		&i.EmailLimit,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesMessagesPlansWithUsageLimits = `-- name: GetNotesMessagesPlansWithUsageLimits :many
SELECT id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at FROM notes_messages_plans 
WHERE text_limit != 'Unlimited Texts'
   OR email_limit != 'Unlimited Emails'
ORDER BY monthly_price
`

// Get plans with usage limits
func (q *Queries) GetNotesMessagesPlansWithUsageLimits(ctx context.Context) ([]NotesMessagesPlan, error) {
	rows, err := q.db.Query(ctx, getNotesMessagesPlansWithUsageLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotesMessagesPlan
	for rows.Next() {
		var i NotesMessagesPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.TextLimit,
			&i.EmailLimit,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesMessagesPlansWithUserLimits = `-- name: GetNotesMessagesPlansWithUserLimits :many
SELECT id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at FROM notes_messages_plans 
WHERE user_limit != 'Unlimited Users'
ORDER BY monthly_price
`

// Get plans with user limits
func (q *Queries) GetNotesMessagesPlansWithUserLimits(ctx context.Context) ([]NotesMessagesPlan, error) {
	rows, err := q.db.Query(ctx, getNotesMessagesPlansWithUserLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotesMessagesPlan
	for rows.Next() {
		var i NotesMessagesPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.TextLimit,
			&i.EmailLimit,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesMessagesPlans = `-- name: ListNotesMessagesPlans :many
SELECT id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at FROM notes_messages_plans ORDER BY monthly_price
`

// Get all notes and messages plans
func (q *Queries) ListNotesMessagesPlans(ctx context.Context) ([]NotesMessagesPlan, error) {
	rows, err := q.db.Query(ctx, listNotesMessagesPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotesMessagesPlan
	for rows.Next() {
		var i NotesMessagesPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.TextLimit,
			&i.EmailLimit,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesMessagesPlansPaginated = `-- name: ListNotesMessagesPlansPaginated :many
SELECT id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at FROM notes_messages_plans 
ORDER BY monthly_price
LIMIT $1 OFFSET $2
`

type ListNotesMessagesPlansPaginatedParams struct {
	Limit  int32
	Offset int32
}

// Get all notes and messages plans with pagination
func (q *Queries) ListNotesMessagesPlansPaginated(ctx context.Context, arg ListNotesMessagesPlansPaginatedParams) ([]NotesMessagesPlan, error) {
	rows, err := q.db.Query(ctx, listNotesMessagesPlansPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotesMessagesPlan
	for rows.Next() {
		var i NotesMessagesPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.TextLimit,
			&i.EmailLimit,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotesMessagesPlan = `-- name: UpdateNotesMessagesPlan :one
UPDATE notes_messages_plans
SET name = $2,
    monthly_price = $3,
    text_limit = $4,
    email_limit = $5,
    user_limit = $6,
    is_most_popular = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, monthly_price, text_limit, email_limit, user_limit, is_most_popular, created_at, updated_at
`

type UpdateNotesMessagesPlanParams struct {
	ID            uuid.UUID
	Name          string
	MonthlyPrice  float64
	TextLimit     *string
	EmailLimit    *string
	UserLimit     *string
	IsMostPopular *bool
}

// Update an existing notes and messages plan
func (q *Queries) UpdateNotesMessagesPlan(ctx context.Context, arg UpdateNotesMessagesPlanParams) (NotesMessagesPlan, error) {
	row := q.db.QueryRow(ctx, updateNotesMessagesPlan,
		arg.ID,
		arg.Name,
		arg.MonthlyPrice,
		arg.TextLimit,
		arg.EmailLimit,
		arg.UserLimit,
		arg.IsMostPopular,
	)
	var i NotesMessagesPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.TextLimit,
		&i.EmailLimit,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
