// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notification_preferences.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationPreference = `-- name: CreateNotificationPreference :one
INSERT INTO notification_preferences (
    user_id,
    notification_type,
    enabled,
    delivery_method
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, notification_type, enabled, delivery_method, created_at, updated_at
`

type CreateNotificationPreferenceParams struct {
	UserID           uuid.UUID
	NotificationType string
	Enabled          *bool
	DeliveryMethod   *string
}

func (q *Queries) CreateNotificationPreference(ctx context.Context, arg CreateNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, createNotificationPreference,
		arg.UserID,
		arg.NotificationType,
		arg.Enabled,
		arg.DeliveryMethod,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.Enabled,
		&i.DeliveryMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationPreference = `-- name: DeleteNotificationPreference :exec
DELETE FROM notification_preferences
WHERE user_id = $1 AND notification_type = $2
`

type DeleteNotificationPreferenceParams struct {
	UserID           uuid.UUID
	NotificationType string
}

func (q *Queries) DeleteNotificationPreference(ctx context.Context, arg DeleteNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationPreference, arg.UserID, arg.NotificationType)
	return err
}

const getEnabledNotificationPreferences = `-- name: GetEnabledNotificationPreferences :many
SELECT id, user_id, notification_type, enabled, delivery_method, created_at, updated_at FROM notification_preferences
WHERE user_id = $1 AND enabled = TRUE
`

func (q *Queries) GetEnabledNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, getEnabledNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NotificationType,
			&i.Enabled,
			&i.DeliveryMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationPreference = `-- name: GetNotificationPreference :one
SELECT id, user_id, notification_type, enabled, delivery_method, created_at, updated_at FROM notification_preferences
WHERE user_id = $1 AND notification_type = $2
`

type GetNotificationPreferenceParams struct {
	UserID           uuid.UUID
	NotificationType string
}

func (q *Queries) GetNotificationPreference(ctx context.Context, arg GetNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreference, arg.UserID, arg.NotificationType)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.Enabled,
		&i.DeliveryMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :many
SELECT u.email, np.id, np.user_id, np.notification_type, np.enabled, np.delivery_method, np.created_at, np.updated_at 
FROM notification_preferences np
INNER JOIN users u on np.user_id = u.id
WHERE np.user_id = $1
ORDER BY notification_type
`

type GetNotificationPreferencesRow struct {
	Email            string
	ID               uuid.UUID
	UserID           uuid.UUID
	NotificationType string
	Enabled          *bool
	DeliveryMethod   *string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]GetNotificationPreferencesRow, error) {
	rows, err := q.db.Query(ctx, getNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationPreferencesRow
	for rows.Next() {
		var i GetNotificationPreferencesRow
		if err := rows.Scan(
			&i.Email,
			&i.ID,
			&i.UserID,
			&i.NotificationType,
			&i.Enabled,
			&i.DeliveryMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationPreference = `-- name: UpdateNotificationPreference :one
UPDATE notification_preferences
SET enabled = $3, delivery_method = $4, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND notification_type = $2
RETURNING id, user_id, notification_type, enabled, delivery_method, created_at, updated_at
`

type UpdateNotificationPreferenceParams struct {
	UserID           uuid.UUID
	NotificationType string
	Enabled          *bool
	DeliveryMethod   *string
}

func (q *Queries) UpdateNotificationPreference(ctx context.Context, arg UpdateNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, updateNotificationPreference,
		arg.UserID,
		arg.NotificationType,
		arg.Enabled,
		arg.DeliveryMethod,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.Enabled,
		&i.DeliveryMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO notification_preferences (
    user_id,
    notification_type,
    enabled,
    delivery_method
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (user_id, notification_type) 
DO UPDATE SET
    enabled = EXCLUDED.enabled,
    delivery_method = EXCLUDED.delivery_method,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, notification_type, enabled, delivery_method, created_at, updated_at
`

type UpsertNotificationPreferenceParams struct {
	UserID           uuid.UUID
	NotificationType string
	Enabled          *bool
	DeliveryMethod   *string
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.NotificationType,
		arg.Enabled,
		arg.DeliveryMethod,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.Enabled,
		&i.DeliveryMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
