// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsWithFilters = `-- name: CountNotificationsWithFilters :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
  AND organization_id = $2
  AND ($3 = '00000000-0000-0000-0000-000000000000'::uuid OR marina_id = $3)
  AND ($4 = '' OR (
    LOWER(title) LIKE LOWER('%' || $4 || '%') OR
    LOWER(content) LIKE LOWER('%' || $4 || '%')
  ))
  AND ($5::text = '' OR read = $5::boolean)
  AND ($6 = '' OR type = $6)
`

type CountNotificationsWithFiltersParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Column3        interface{}
	Column4        interface{}
	Column5        string
	Column6        interface{}
}

func (q *Queries) CountNotificationsWithFilters(ctx context.Context, arg CountNotificationsWithFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsWithFilters,
		arg.UserID,
		arg.OrganizationID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    organization_id,
    marina_id,
    type,
    title,
    content,
    data,
    priority
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, organization_id, marina_id, type, title, content, data, read, read_at, priority, created_at, updated_at
`

type CreateNotificationParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	Type           string
	Title          string
	Content        string
	Data           []byte
	Priority       *string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.OrganizationID,
		arg.MarinaID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.Data,
		arg.Priority,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Data,
		&i.Read,
		&i.ReadAt,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < $1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, organization_id, marina_id, type, title, content, data, read, read_at, priority, created_at, updated_at FROM notifications
WHERE id = $1 AND user_id = $2
`

type GetNotificationByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Data,
		&i.Read,
		&i.ReadAt,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationsByType = `-- name: GetNotificationsByType :many
SELECT id, user_id, organization_id, marina_id, type, title, content, data, read, read_at, priority, created_at, updated_at FROM notifications
WHERE user_id = $1
AND organization_id = $2
AND type = $3
AND ($4::uuid IS NULL OR marina_id = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type GetNotificationsByTypeParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Type           string
	Column4        uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByType,
		arg.UserID,
		arg.OrganizationID,
		arg.Type,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Data,
			&i.Read,
			&i.ReadAt,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) as count FROM notifications
WHERE user_id = $1
AND organization_id = $2
AND ($3::uuid IS NULL OR marina_id = $3)
AND read = FALSE
`

type GetUnreadNotificationCountParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Column3        uuid.UUID
}

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, arg GetUnreadNotificationCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, arg.UserID, arg.OrganizationID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, organization_id, marina_id, type, title, content, data, read, read_at, priority, created_at, updated_at FROM notifications
WHERE user_id = $1
AND organization_id = $2
AND ($3::uuid IS NULL OR marina_id = $3)
ORDER BY 
    CASE WHEN priority = 'urgent' THEN 1
         WHEN priority = 'high' THEN 2
         WHEN priority = 'normal' THEN 3
         WHEN priority = 'low' THEN 4
         ELSE 5 END,
    created_at DESC
LIMIT $4 OFFSET $5
`

type ListNotificationsParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Column3        uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.OrganizationID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Data,
			&i.Read,
			&i.ReadAt,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsWithFilters = `-- name: ListNotificationsWithFilters :many
SELECT id, user_id, organization_id, marina_id, type, title, content, data, read, read_at, priority, created_at, updated_at FROM notifications
WHERE user_id = $1
  AND organization_id = $2
  AND ($3 = '00000000-0000-0000-0000-000000000000'::uuid OR marina_id = $3)
  AND ($4 = '' OR (
    LOWER(title) LIKE LOWER('%' || $4 || '%') OR
    LOWER(content) LIKE LOWER('%' || $4 || '%')
  ))
  AND ($5::text = '' OR read = $5::boolean)
  AND ($6 = '' OR type = $6)
ORDER BY 
  -- Mantener prioridad como orden principal si no se especifica sort
  CASE 
    WHEN $7 = '' THEN (
      CASE WHEN priority = 'urgent' THEN 1
           WHEN priority = 'high' THEN 2
           WHEN priority = 'normal' THEN 3
           WHEN priority = 'low' THEN 4
           ELSE 5 END
    )
  END,
  -- Sorting dinámico opcional
  CASE 
    WHEN $7 = 'type' AND $8 = 'asc' THEN type
    WHEN $7 = 'title' AND $8 = 'asc' THEN title
  END ASC,
  CASE 
    WHEN $7 = 'type' AND $8 = 'desc' THEN type
    WHEN $7 = 'title' AND $8 = 'desc' THEN title
  END DESC,
  CASE 
    WHEN $7 = 'read' AND $8 = 'asc' THEN read
  END ASC,
  CASE 
    WHEN $7 = 'read' AND $8 = 'desc' THEN read
  END DESC,
  CASE 
    WHEN $7 = 'created_at' AND $8 = 'asc' THEN created_at
  END ASC,
  CASE 
    WHEN $7 = 'created_at' AND $8 = 'desc' THEN created_at
    ELSE created_at
  END DESC
LIMIT $9 OFFSET $10
`

type ListNotificationsWithFiltersParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Column3        interface{}
	Column4        interface{}
	Column5        string
	Column6        interface{}
	Column7        interface{}
	Column8        interface{}
	Limit          int32
	Offset         int32
}

func (q *Queries) ListNotificationsWithFilters(ctx context.Context, arg ListNotificationsWithFiltersParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsWithFilters,
		arg.UserID,
		arg.OrganizationID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Data,
			&i.Read,
			&i.ReadAt,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, organization_id, marina_id, type, title, content, data, read, read_at, priority, created_at, updated_at FROM notifications
WHERE user_id = $1
AND organization_id = $2
AND ($3::uuid IS NULL OR marina_id = $3)
AND read = FALSE
ORDER BY 
    CASE WHEN priority = 'urgent' THEN 1
         WHEN priority = 'high' THEN 2
         WHEN priority = 'normal' THEN 3
         WHEN priority = 'low' THEN 4
         ELSE 5 END,
    created_at DESC
LIMIT $4 OFFSET $5
`

type ListUnreadNotificationsParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Column3        uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications,
		arg.UserID,
		arg.OrganizationID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.MarinaID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Data,
			&i.Read,
			&i.ReadAt,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET read = TRUE, read_at = CURRENT_TIMESTAMP
WHERE user_id = $1
AND organization_id = $2
AND ($3::uuid IS NULL OR marina_id = $3)
AND read = FALSE
`

type MarkAllNotificationsAsReadParams struct {
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Column3        uuid.UUID
}

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, arg MarkAllNotificationsAsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, arg.UserID, arg.OrganizationID, arg.Column3)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET read = TRUE, read_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, organization_id, marina_id, type, title, content, data, read, read_at, priority, created_at, updated_at
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.MarinaID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Data,
		&i.Read,
		&i.ReadAt,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
