// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
        email,
        name,
        image,
        website,
        country,
        phone,
        is_active,
        is_test,
        address_id
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, email, name, image, website, country, phone, is_active, is_test, created_at, updated_at, deleted_at, address_id
`

type CreateOrganizationParams struct {
	Email     string
	Name      string
	Image     *string
	Website   *string
	Country   *string
	Phone     *string
	IsActive  *bool
	IsTest    *bool
	AddressID uuid.UUID
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Email,
		arg.Name,
		arg.Image,
		arg.Website,
		arg.Country,
		arg.Phone,
		arg.IsActive,
		arg.IsTest,
		arg.AddressID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Website,
		&i.Country,
		&i.Phone,
		&i.IsActive,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AddressID,
	)
	return i, err
}

const getAllOrganizations = `-- name: GetAllOrganizations :many
SELECT id, email, name, image, website, country, phone, is_active, is_test, created_at, updated_at, deleted_at, address_id
FROM organizations
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getAllOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Image,
			&i.Website,
			&i.Country,
			&i.Phone,
			&i.IsActive,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AddressID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationByEmail = `-- name: GetOrganizationByEmail :one
SELECT id, email, name, image, website, country, phone, is_active, is_test, created_at, updated_at, deleted_at, address_id
FROM organizations
WHERE email = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByEmail(ctx context.Context, email string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByEmail, email)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Website,
		&i.Country,
		&i.Phone,
		&i.IsActive,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AddressID,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, email, name, image, website, country, phone, is_active, is_test, created_at, updated_at, deleted_at, address_id
FROM organizations
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Website,
		&i.Country,
		&i.Phone,
		&i.IsActive,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AddressID,
	)
	return i, err
}

const getOrganizationsPaginated = `-- name: GetOrganizationsPaginated :many
SELECT id, email, name, image, website, country, phone, is_active, is_test, created_at, updated_at, deleted_at, address_id
FROM organizations
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetOrganizationsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetOrganizationsPaginated(ctx context.Context, arg GetOrganizationsPaginatedParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getOrganizationsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Image,
			&i.Website,
			&i.Country,
			&i.Phone,
			&i.IsActive,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AddressID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, id)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET email = $2,
    name = $3,
    image = $4,
    website = $5,
    country = $6,
    phone = $7,
    is_active = $8,
    is_test = $9,
    updated_at = CURRENT_TIMESTAMP,
    address_id = $10
WHERE id = $1
RETURNING id, email, name, image, website, country, phone, is_active, is_test, created_at, updated_at, deleted_at, address_id
`

type UpdateOrganizationParams struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Image     *string
	Website   *string
	Country   *string
	Phone     *string
	IsActive  *bool
	IsTest    *bool
	AddressID uuid.UUID
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Image,
		arg.Website,
		arg.Country,
		arg.Phone,
		arg.IsActive,
		arg.IsTest,
		arg.AddressID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Website,
		&i.Country,
		&i.Phone,
		&i.IsActive,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AddressID,
	)
	return i, err
}
