// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentLink = `-- name: CreatePaymentLink :one
INSERT INTO payment_links (
    token,
    organization_id,
    marina_id,
    customer_id,
    scope,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, token, organization_id, marina_id, customer_id, scope, expires_at, used, revoked, created_at, used_at, revoked_at
`

type CreatePaymentLinkParams struct {
	Token          string
	OrganizationID uuid.UUID
	MarinaID       uuid.UUID
	CustomerID     string
	Scope          string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, createPaymentLink,
		arg.Token,
		arg.OrganizationID,
		arg.MarinaID,
		arg.CustomerID,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OrganizationID,
		&i.MarinaID,
		&i.CustomerID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Used,
		&i.Revoked,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getValidPaymentLinkByToken = `-- name: GetValidPaymentLinkByToken :one
SELECT id, token, organization_id, marina_id, customer_id, scope, expires_at, used, revoked, created_at, used_at, revoked_at FROM payment_links
WHERE token = $1 AND used = FALSE AND revoked = FALSE AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetValidPaymentLinkByToken(ctx context.Context, token string) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, getValidPaymentLinkByToken, token)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OrganizationID,
		&i.MarinaID,
		&i.CustomerID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Used,
		&i.Revoked,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActivePaymentLinksByCustomer = `-- name: ListActivePaymentLinksByCustomer :many
SELECT id, token, organization_id, marina_id, customer_id, scope, expires_at, used, revoked, created_at, used_at, revoked_at FROM payment_links
WHERE customer_id = $1 AND marina_id = $2 AND revoked = FALSE AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

type ListActivePaymentLinksByCustomerParams struct {
	CustomerID string
	MarinaID   uuid.UUID
}

func (q *Queries) ListActivePaymentLinksByCustomer(ctx context.Context, arg ListActivePaymentLinksByCustomerParams) ([]PaymentLink, error) {
	rows, err := q.db.Query(ctx, listActivePaymentLinksByCustomer, arg.CustomerID, arg.MarinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentLink
	for rows.Next() {
		var i PaymentLink
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.OrganizationID,
			&i.MarinaID,
			&i.CustomerID,
			&i.Scope,
			&i.ExpiresAt,
			&i.Used,
			&i.Revoked,
			&i.CreatedAt,
			&i.UsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentLinkUsed = `-- name: MarkPaymentLinkUsed :one
UPDATE payment_links
SET used = TRUE, used_at = CURRENT_TIMESTAMP
WHERE token = $1 AND used = FALSE AND revoked = FALSE AND expires_at > CURRENT_TIMESTAMP
RETURNING id, token, organization_id, marina_id, customer_id, scope, expires_at, used, revoked, created_at, used_at, revoked_at
`

func (q *Queries) MarkPaymentLinkUsed(ctx context.Context, token string) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, markPaymentLinkUsed, token)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OrganizationID,
		&i.MarinaID,
		&i.CustomerID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Used,
		&i.Revoked,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokePaymentLink = `-- name: RevokePaymentLink :one
UPDATE payment_links
SET revoked = TRUE, revoked_at = CURRENT_TIMESTAMP
WHERE token = $1 AND revoked = FALSE
RETURNING id, token, organization_id, marina_id, customer_id, scope, expires_at, used, revoked, created_at, used_at, revoked_at
`

func (q *Queries) RevokePaymentLink(ctx context.Context, token string) (PaymentLink, error) {
	row := q.db.QueryRow(ctx, revokePaymentLink, token)
	var i PaymentLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.OrganizationID,
		&i.MarinaID,
		&i.CustomerID,
		&i.Scope,
		&i.ExpiresAt,
		&i.Used,
		&i.Revoked,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}
