// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_tax.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTaxConfigurationsByMarinas = `-- name: CountTaxConfigurationsByMarinas :one
SELECT COUNT(*) FROM tax_configurations
WHERE marina_id = ANY($1::uuid[])
`

func (q *Queries) CountTaxConfigurationsByMarinas(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaxConfigurationsByMarinas, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTaxConfiguration = `-- name: CreateTaxConfiguration :one
INSERT INTO tax_configurations (
    marina_id,
    convenience_fee,
    convenience_fee_type,
    convenience_fee_enabled,
    convenience_fee_description,
    surcharge,
    surcharge_type,
    surcharge_enabled,
    surcharge_description,
    payment_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, marina_id, convenience_fee, convenience_fee_type, convenience_fee_enabled, convenience_fee_description, surcharge, surcharge_type, surcharge_enabled, surcharge_description, payment_type, created_at, updated_at
`

type CreateTaxConfigurationParams struct {
	MarinaID                  uuid.UUID
	ConvenienceFee            pgtype.Numeric
	ConvenienceFeeType        string
	ConvenienceFeeEnabled     bool
	ConvenienceFeeDescription *string
	Surcharge                 pgtype.Numeric
	SurchargeType             string
	SurchargeEnabled          bool
	SurchargeDescription      *string
	PaymentType               string
}

func (q *Queries) CreateTaxConfiguration(ctx context.Context, arg CreateTaxConfigurationParams) (TaxConfiguration, error) {
	row := q.db.QueryRow(ctx, createTaxConfiguration,
		arg.MarinaID,
		arg.ConvenienceFee,
		arg.ConvenienceFeeType,
		arg.ConvenienceFeeEnabled,
		arg.ConvenienceFeeDescription,
		arg.Surcharge,
		arg.SurchargeType,
		arg.SurchargeEnabled,
		arg.SurchargeDescription,
		arg.PaymentType,
	)
	var i TaxConfiguration
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.ConvenienceFee,
		&i.ConvenienceFeeType,
		&i.ConvenienceFeeEnabled,
		&i.ConvenienceFeeDescription,
		&i.Surcharge,
		&i.SurchargeType,
		&i.SurchargeEnabled,
		&i.SurchargeDescription,
		&i.PaymentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaxConfiguration = `-- name: DeleteTaxConfiguration :exec
DELETE FROM tax_configurations
WHERE id = $1
`

func (q *Queries) DeleteTaxConfiguration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaxConfiguration, id)
	return err
}

const getAllTaxConfigurationsByMarinaID = `-- name: GetAllTaxConfigurationsByMarinaID :many
SELECT id, marina_id, convenience_fee, convenience_fee_type, convenience_fee_enabled, convenience_fee_description, surcharge, surcharge_type, surcharge_enabled, surcharge_description, payment_type, created_at, updated_at FROM tax_configurations
WHERE marina_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllTaxConfigurationsByMarinaID(ctx context.Context, marinaID uuid.UUID) ([]TaxConfiguration, error) {
	rows, err := q.db.Query(ctx, getAllTaxConfigurationsByMarinaID, marinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxConfiguration
	for rows.Next() {
		var i TaxConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.ConvenienceFee,
			&i.ConvenienceFeeType,
			&i.ConvenienceFeeEnabled,
			&i.ConvenienceFeeDescription,
			&i.Surcharge,
			&i.SurchargeType,
			&i.SurchargeEnabled,
			&i.SurchargeDescription,
			&i.PaymentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaxConfigurationByID = `-- name: GetTaxConfigurationByID :one
SELECT id, marina_id, convenience_fee, convenience_fee_type, convenience_fee_enabled, convenience_fee_description, surcharge, surcharge_type, surcharge_enabled, surcharge_description, payment_type, created_at, updated_at FROM tax_configurations
WHERE id = $1
`

func (q *Queries) GetTaxConfigurationByID(ctx context.Context, id uuid.UUID) (TaxConfiguration, error) {
	row := q.db.QueryRow(ctx, getTaxConfigurationByID, id)
	var i TaxConfiguration
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.ConvenienceFee,
		&i.ConvenienceFeeType,
		&i.ConvenienceFeeEnabled,
		&i.ConvenienceFeeDescription,
		&i.Surcharge,
		&i.SurchargeType,
		&i.SurchargeEnabled,
		&i.SurchargeDescription,
		&i.PaymentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxConfigurationByMarinaAndPaymentType = `-- name: GetTaxConfigurationByMarinaAndPaymentType :one
SELECT id, marina_id, convenience_fee, convenience_fee_type, convenience_fee_enabled, convenience_fee_description, surcharge, surcharge_type, surcharge_enabled, surcharge_description, payment_type, created_at, updated_at FROM tax_configurations
WHERE marina_id = $1 
    AND payment_type = $2
LIMIT 1
`

type GetTaxConfigurationByMarinaAndPaymentTypeParams struct {
	MarinaID    uuid.UUID
	PaymentType string
}

func (q *Queries) GetTaxConfigurationByMarinaAndPaymentType(ctx context.Context, arg GetTaxConfigurationByMarinaAndPaymentTypeParams) (TaxConfiguration, error) {
	row := q.db.QueryRow(ctx, getTaxConfigurationByMarinaAndPaymentType, arg.MarinaID, arg.PaymentType)
	var i TaxConfiguration
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.ConvenienceFee,
		&i.ConvenienceFeeType,
		&i.ConvenienceFeeEnabled,
		&i.ConvenienceFeeDescription,
		&i.Surcharge,
		&i.SurchargeType,
		&i.SurchargeEnabled,
		&i.SurchargeDescription,
		&i.PaymentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxConfigurationForCalculation = `-- name: GetTaxConfigurationForCalculation :one
SELECT 
    convenience_fee,
    convenience_fee_type,
    convenience_fee_enabled,
    surcharge,
    surcharge_type,
    surcharge_enabled,
    payment_type
FROM tax_configurations
WHERE id = $1
`

type GetTaxConfigurationForCalculationRow struct {
	ConvenienceFee        pgtype.Numeric
	ConvenienceFeeType    string
	ConvenienceFeeEnabled bool
	Surcharge             pgtype.Numeric
	SurchargeType         string
	SurchargeEnabled      bool
	PaymentType           string
}

func (q *Queries) GetTaxConfigurationForCalculation(ctx context.Context, id uuid.UUID) (GetTaxConfigurationForCalculationRow, error) {
	row := q.db.QueryRow(ctx, getTaxConfigurationForCalculation, id)
	var i GetTaxConfigurationForCalculationRow
	err := row.Scan(
		&i.ConvenienceFee,
		&i.ConvenienceFeeType,
		&i.ConvenienceFeeEnabled,
		&i.Surcharge,
		&i.SurchargeType,
		&i.SurchargeEnabled,
		&i.PaymentType,
	)
	return i, err
}

const listTaxConfigurations = `-- name: ListTaxConfigurations :many
SELECT id, marina_id, convenience_fee, convenience_fee_type, convenience_fee_enabled, convenience_fee_description, surcharge, surcharge_type, surcharge_enabled, surcharge_description, payment_type, created_at, updated_at FROM tax_configurations
WHERE marina_id = ANY($1::uuid[])
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTaxConfigurationsParams struct {
	Column1 []uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListTaxConfigurations(ctx context.Context, arg ListTaxConfigurationsParams) ([]TaxConfiguration, error) {
	rows, err := q.db.Query(ctx, listTaxConfigurations, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxConfiguration
	for rows.Next() {
		var i TaxConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.MarinaID,
			&i.ConvenienceFee,
			&i.ConvenienceFeeType,
			&i.ConvenienceFeeEnabled,
			&i.ConvenienceFeeDescription,
			&i.Surcharge,
			&i.SurchargeType,
			&i.SurchargeEnabled,
			&i.SurchargeDescription,
			&i.PaymentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaxConfiguration = `-- name: UpdateTaxConfiguration :one
UPDATE tax_configurations
SET 
    convenience_fee = COALESCE($1, convenience_fee),
    convenience_fee_type = COALESCE($2, convenience_fee_type),
    convenience_fee_enabled = COALESCE($3, convenience_fee_enabled),
    convenience_fee_description = COALESCE($4, convenience_fee_description),
    surcharge = COALESCE($5, surcharge),
    surcharge_type = COALESCE($6, surcharge_type),
    surcharge_enabled = COALESCE($7, surcharge_enabled),
    surcharge_description = COALESCE($8, surcharge_description),
    payment_type = COALESCE($9, payment_type),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $10
RETURNING id, marina_id, convenience_fee, convenience_fee_type, convenience_fee_enabled, convenience_fee_description, surcharge, surcharge_type, surcharge_enabled, surcharge_description, payment_type, created_at, updated_at
`

type UpdateTaxConfigurationParams struct {
	ConvenienceFee            float64
	ConvenienceFeeType        *string
	ConvenienceFeeEnabled     *bool
	ConvenienceFeeDescription *string
	Surcharge                 float64
	SurchargeType             *string
	SurchargeEnabled          *bool
	SurchargeDescription      *string
	PaymentType               *string
	ID                        uuid.UUID
}

func (q *Queries) UpdateTaxConfiguration(ctx context.Context, arg UpdateTaxConfigurationParams) (TaxConfiguration, error) {
	row := q.db.QueryRow(ctx, updateTaxConfiguration,
		arg.ConvenienceFee,
		arg.ConvenienceFeeType,
		arg.ConvenienceFeeEnabled,
		arg.ConvenienceFeeDescription,
		arg.Surcharge,
		arg.SurchargeType,
		arg.SurchargeEnabled,
		arg.SurchargeDescription,
		arg.PaymentType,
		arg.ID,
	)
	var i TaxConfiguration
	err := row.Scan(
		&i.ID,
		&i.MarinaID,
		&i.ConvenienceFee,
		&i.ConvenienceFeeType,
		&i.ConvenienceFeeEnabled,
		&i.ConvenienceFeeDescription,
		&i.Surcharge,
		&i.SurchargeType,
		&i.SurchargeEnabled,
		&i.SurchargeDescription,
		&i.PaymentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
