// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countRolesByMarina = `-- name: CountRolesByMarina :one
SELECT COUNT(*)
FROM roles
WHERE deleted_at IS NULL
    AND (marina_id IS NULL OR marina_id = $1)
    AND type != 'internal'
`

func (q *Queries) CountRolesByMarina(ctx context.Context, marinaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRolesByMarina, marinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, permissions, is_active, is_customer_role, type, marina_id)
VALUES ($1, $2, $3, $4, $5, $6, NULLIF($7::uuid, '00000000-0000-0000-0000-000000000000'))
RETURNING id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
`

type CreateRoleParams struct {
	Name           string
	Description    *string
	Permissions    []byte
	IsActive       *bool
	IsCustomerRole *bool
	Type           string
	Column7        uuid.UUID
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.IsActive,
		arg.IsCustomerRole,
		arg.Type,
		arg.Column7,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCustomerRole,
		&i.Type,
		&i.MarinaID,
	)
	return i, err
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE deleted_at IS NULL
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCustomerRole,
			&i.Type,
			&i.MarinaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRolesByType = `-- name: GetAllRolesByType :many
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE deleted_at IS NULL
    AND type = $1
`

func (q *Queries) GetAllRolesByType(ctx context.Context, type_ string) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRolesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCustomerRole,
			&i.Type,
			&i.MarinaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRolesByTypePaginated = `-- name: GetAllRolesByTypePaginated :many
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE deleted_at IS NULL
    AND type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllRolesByTypePaginatedParams struct {
	Type   string
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllRolesByTypePaginated(ctx context.Context, arg GetAllRolesByTypePaginatedParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRolesByTypePaginated, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCustomerRole,
			&i.Type,
			&i.MarinaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRolesByTypes = `-- name: GetAllRolesByTypes :many
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE deleted_at IS NULL
    AND type = ANY($1::text[])
ORDER BY created_at DESC
`

func (q *Queries) GetAllRolesByTypes(ctx context.Context, dollar_1 []string) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRolesByTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCustomerRole,
			&i.Type,
			&i.MarinaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRolesByTypesPaginated = `-- name: GetAllRolesByTypesPaginated :many
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE deleted_at IS NULL
    AND type = ANY($1::text[])
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllRolesByTypesPaginatedParams struct {
	Column1 []string
	Limit   int32
	Offset  int32
}

func (q *Queries) GetAllRolesByTypesPaginated(ctx context.Context, arg GetAllRolesByTypesPaginatedParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRolesByTypesPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCustomerRole,
			&i.Type,
			&i.MarinaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCustomerRole,
		&i.Type,
		&i.MarinaID,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE name = $1
    AND deleted_at IS NULL
    AND marina_id IS NULL
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCustomerRole,
		&i.Type,
		&i.MarinaID,
	)
	return i, err
}

const getRoleByNameAndMarina = `-- name: GetRoleByNameAndMarina :one
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE name = $1
    AND marina_id = $2
    AND deleted_at IS NULL
`

type GetRoleByNameAndMarinaParams struct {
	Name     string
	MarinaID uuid.UUID
}

func (q *Queries) GetRoleByNameAndMarina(ctx context.Context, arg GetRoleByNameAndMarinaParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByNameAndMarina, arg.Name, arg.MarinaID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCustomerRole,
		&i.Type,
		&i.MarinaID,
	)
	return i, err
}

const getRolesPaginated = `-- name: GetRolesPaginated :many
SELECT id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
FROM roles
WHERE deleted_at IS NULL
    AND (marina_id IS NULL OR marina_id = $1)
    AND type != 'internal'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetRolesPaginatedParams struct {
	MarinaID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetRolesPaginated(ctx context.Context, arg GetRolesPaginatedParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesPaginated, arg.MarinaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsCustomerRole,
			&i.Type,
			&i.MarinaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE roles
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteRole, id)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2,
    description = $3,
    permissions = $4,
    is_active = $5,
    is_customer_role = $6,
    type = $7,
    marina_id = NULLIF($8::uuid, '00000000-0000-0000-0000-000000000000'),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, permissions, is_active, created_at, updated_at, deleted_at, is_customer_role, type, marina_id
`

type UpdateRoleParams struct {
	ID             uuid.UUID
	Name           string
	Description    *string
	Permissions    []byte
	IsActive       *bool
	IsCustomerRole *bool
	Type           string
	Column8        uuid.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.IsActive,
		arg.IsCustomerRole,
		arg.Type,
		arg.Column8,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsCustomerRole,
		&i.Type,
		&i.MarinaID,
	)
	return i, err
}
