// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: storage_plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStoragePlan = `-- name: CreateStoragePlan :one
INSERT INTO storage_plans (
    name,
    monthly_price,
    storage_limit_gb,
    user_limit,
    is_most_popular
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at
`

type CreateStoragePlanParams struct {
	Name           string
	MonthlyPrice   float64
	StorageLimitGb *string
	UserLimit      *string
	IsMostPopular  *bool
}

// Create a new storage plan
func (q *Queries) CreateStoragePlan(ctx context.Context, arg CreateStoragePlanParams) (StoragePlan, error) {
	row := q.db.QueryRow(ctx, createStoragePlan,
		arg.Name,
		arg.MonthlyPrice,
		arg.StorageLimitGb,
		arg.UserLimit,
		arg.IsMostPopular,
	)
	var i StoragePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.StorageLimitGb,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMarinaStoragePlan = `-- name: GetMarinaStoragePlan :one
SELECT sp.id, sp.name, sp.monthly_price, sp.storage_limit_gb, sp.user_limit, sp.is_most_popular, sp.created_at, sp.updated_at 
FROM storage_plans sp
JOIN marinas m ON m.storage_plan_id = sp.id
WHERE m.id = $1
`

// Get marina's current plan
func (q *Queries) GetMarinaStoragePlan(ctx context.Context, id uuid.UUID) (StoragePlan, error) {
	row := q.db.QueryRow(ctx, getMarinaStoragePlan, id)
	var i StoragePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.StorageLimitGb,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMostPopularStoragePlan = `-- name: GetMostPopularStoragePlan :one
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans WHERE is_most_popular = true LIMIT 1
`

// Get the most popular plan
func (q *Queries) GetMostPopularStoragePlan(ctx context.Context) (StoragePlan, error) {
	row := q.db.QueryRow(ctx, getMostPopularStoragePlan)
	var i StoragePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.StorageLimitGb,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoragePlanByID = `-- name: GetStoragePlanByID :one
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans WHERE id = $1
`

// Get a specific plan by ID
func (q *Queries) GetStoragePlanByID(ctx context.Context, id uuid.UUID) (StoragePlan, error) {
	row := q.db.QueryRow(ctx, getStoragePlanByID, id)
	var i StoragePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.StorageLimitGb,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoragePlanByName = `-- name: GetStoragePlanByName :one
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans WHERE name = $1
`

// Get plan by name
func (q *Queries) GetStoragePlanByName(ctx context.Context, name string) (StoragePlan, error) {
	row := q.db.QueryRow(ctx, getStoragePlanByName, name)
	var i StoragePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.StorageLimitGb,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoragePlansInPriceRange = `-- name: GetStoragePlansInPriceRange :many
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans 
WHERE monthly_price BETWEEN $1 AND $2
ORDER BY monthly_price
`

type GetStoragePlansInPriceRangeParams struct {
	MonthlyPrice   float64
	MonthlyPrice_2 float64
}

// Get plans within a specific price range
func (q *Queries) GetStoragePlansInPriceRange(ctx context.Context, arg GetStoragePlansInPriceRangeParams) ([]StoragePlan, error) {
	rows, err := q.db.Query(ctx, getStoragePlansInPriceRange, arg.MonthlyPrice, arg.MonthlyPrice_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoragePlan
	for rows.Next() {
		var i StoragePlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.StorageLimitGb,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoragePlansWithStorageLimits = `-- name: GetStoragePlansWithStorageLimits :many
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans 
WHERE storage_limit_gb != 'Unlimited Storage'
ORDER BY monthly_price
`

// Get plans with storage limits
func (q *Queries) GetStoragePlansWithStorageLimits(ctx context.Context) ([]StoragePlan, error) {
	rows, err := q.db.Query(ctx, getStoragePlansWithStorageLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoragePlan
	for rows.Next() {
		var i StoragePlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.StorageLimitGb,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoragePlansWithUserLimits = `-- name: GetStoragePlansWithUserLimits :many
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans 
WHERE user_limit != 'Unlimited Users'
ORDER BY monthly_price
`

// Get plans with user limits
func (q *Queries) GetStoragePlansWithUserLimits(ctx context.Context) ([]StoragePlan, error) {
	rows, err := q.db.Query(ctx, getStoragePlansWithUserLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoragePlan
	for rows.Next() {
		var i StoragePlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.StorageLimitGb,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragePlans = `-- name: ListStoragePlans :many
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans ORDER BY monthly_price
`

// Get all storage plans
func (q *Queries) ListStoragePlans(ctx context.Context) ([]StoragePlan, error) {
	rows, err := q.db.Query(ctx, listStoragePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoragePlan
	for rows.Next() {
		var i StoragePlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.StorageLimitGb,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragePlansPaginated = `-- name: ListStoragePlansPaginated :many
SELECT id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at FROM storage_plans 
ORDER BY monthly_price
LIMIT $1 OFFSET $2
`

type ListStoragePlansPaginatedParams struct {
	Limit  int32
	Offset int32
}

// Get all storage plans with pagination
func (q *Queries) ListStoragePlansPaginated(ctx context.Context, arg ListStoragePlansPaginatedParams) ([]StoragePlan, error) {
	rows, err := q.db.Query(ctx, listStoragePlansPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoragePlan
	for rows.Next() {
		var i StoragePlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPrice,
			&i.StorageLimitGb,
			&i.UserLimit,
			&i.IsMostPopular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoragePlan = `-- name: UpdateStoragePlan :one
UPDATE storage_plans
SET name = $2,
    monthly_price = $3,
    storage_limit_gb = $4,
    user_limit = $5,
    is_most_popular = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, monthly_price, storage_limit_gb, user_limit, is_most_popular, created_at, updated_at
`

type UpdateStoragePlanParams struct {
	ID             uuid.UUID
	Name           string
	MonthlyPrice   float64
	StorageLimitGb *string
	UserLimit      *string
	IsMostPopular  *bool
}

// Update an existing storage plan
func (q *Queries) UpdateStoragePlan(ctx context.Context, arg UpdateStoragePlanParams) (StoragePlan, error) {
	row := q.db.QueryRow(ctx, updateStoragePlan,
		arg.ID,
		arg.Name,
		arg.MonthlyPrice,
		arg.StorageLimitGb,
		arg.UserLimit,
		arg.IsMostPopular,
	)
	var i StoragePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPrice,
		&i.StorageLimitGb,
		&i.UserLimit,
		&i.IsMostPopular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
