// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_marinas.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserToMarina = `-- name: AssignUserToMarina :exec
INSERT INTO user_marinas (user_id, marina_id, customer_id, role_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, marina_id) DO UPDATE SET role_id = EXCLUDED.role_id
`

type AssignUserToMarinaParams struct {
	UserID     uuid.UUID
	MarinaID   uuid.UUID
	CustomerID *string
	RoleID     uuid.UUID
}

func (q *Queries) AssignUserToMarina(ctx context.Context, arg AssignUserToMarinaParams) error {
	_, err := q.db.Exec(ctx, assignUserToMarina,
		arg.UserID,
		arg.MarinaID,
		arg.CustomerID,
		arg.RoleID,
	)
	return err
}

const countCustomerMarinaUsers = `-- name: CountCustomerMarinaUsers :one
SELECT COUNT(*)
FROM users u
    JOIN user_marinas um ON u.id = um.user_id
WHERE um.marina_id = $1
    AND um.customer_id = $2
    AND u.deleted_at IS NULL
`

type CountCustomerMarinaUsersParams struct {
	MarinaID   uuid.UUID
	CustomerID *string
}

func (q *Queries) CountCustomerMarinaUsers(ctx context.Context, arg CountCustomerMarinaUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomerMarinaUsers, arg.MarinaID, arg.CustomerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMarinasAssignmentsPaginatedAdminOnly = `-- name: CountUserMarinasAssignmentsPaginatedAdminOnly :one
SELECT COUNT(*)
FROM user_marinas um
JOIN users u ON u.id = um.user_id
WHERE um.marina_id = $1
  AND u.is_superuser = TRUE 
  AND u.deleted_at IS NULL
`

func (q *Queries) CountUserMarinasAssignmentsPaginatedAdminOnly(ctx context.Context, marinaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMarinasAssignmentsPaginatedAdminOnly, marinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRoleID = `-- name: CountUsersByRoleID :one
SELECT COUNT(*)
FROM user_marinas um
JOIN roles r ON r.id = um.role_id
WHERE r.id = $1
  AND r.deleted_at IS NULL
`

func (q *Queries) CountUsersByRoleID(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRoleID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersNotAssignedToMarina = `-- name: CountUsersNotAssignedToMarina :one
SELECT COUNT(*)
FROM users u
WHERE u.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM user_marinas um
    WHERE um.user_id = u.id
      AND u.is_superuser = FALSE
      AND um.marina_id = $1
  )
`

func (q *Queries) CountUsersNotAssignedToMarina(ctx context.Context, marinaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersNotAssignedToMarina, marinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersNotAssignedToMarinaAdmin = `-- name: CountUsersNotAssignedToMarinaAdmin :one
SELECT COUNT(*)
FROM users u
WHERE u.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM user_marinas um
    WHERE um.user_id = u.id
      AND um.marina_id = $1
  )
`

func (q *Queries) CountUsersNotAssignedToMarinaAdmin(ctx context.Context, marinaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersNotAssignedToMarinaAdmin, marinaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const customerMarinaUser = `-- name: CustomerMarinaUser :one
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics
FROM users u
    JOIN user_marinas um ON u.id = um.user_id
WHERE um.marina_id = $1
    AND um.customer_id = $2
    AND u.deleted_at IS NULL
`

type CustomerMarinaUserParams struct {
	MarinaID   uuid.UUID
	CustomerID *string
}

func (q *Queries) CustomerMarinaUser(ctx context.Context, arg CustomerMarinaUserParams) (User, error) {
	row := q.db.QueryRow(ctx, customerMarinaUser, arg.MarinaID, arg.CustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const getCustomerMarinaUsersPaginated = `-- name: GetCustomerMarinaUsersPaginated :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics
FROM users u
    JOIN user_marinas um ON u.id = um.user_id
WHERE um.marina_id = $1
    AND um.customer_id = $2
    AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type GetCustomerMarinaUsersPaginatedParams struct {
	MarinaID   uuid.UUID
	CustomerID *string
	Limit      int32
	Offset     int32
}

func (q *Queries) GetCustomerMarinaUsersPaginated(ctx context.Context, arg GetCustomerMarinaUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getCustomerMarinaUsersPaginated,
		arg.MarinaID,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaUsersList = `-- name: GetMarinaUsersList :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
    JOIN user_marinas um ON u.id = um.user_id
    LEFT JOIN roles r ON u.role_id = r.id
WHERE um.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.deleted_at IS NULL
`

type GetMarinaUsersListParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
}

type GetMarinaUsersListRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetMarinaUsersList(ctx context.Context, arg GetMarinaUsersListParams) ([]GetMarinaUsersListRow, error) {
	rows, err := q.db.Query(ctx, getMarinaUsersList, arg.MarinaID, arg.IsCustomer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMarinaUsersListRow
	for rows.Next() {
		var i GetMarinaUsersListRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaUsersListPaginated = `-- name: GetMarinaUsersListPaginated :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
    JOIN user_marinas um ON u.id = um.user_id
    LEFT JOIN roles r ON u.role_id = r.id
WHERE um.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type GetMarinaUsersListPaginatedParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
	Limit      int32
	Offset     int32
}

type GetMarinaUsersListPaginatedRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetMarinaUsersListPaginated(ctx context.Context, arg GetMarinaUsersListPaginatedParams) ([]GetMarinaUsersListPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getMarinaUsersListPaginated,
		arg.MarinaID,
		arg.IsCustomer,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMarinaUsersListPaginatedRow
	for rows.Next() {
		var i GetMarinaUsersListPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMarinaAssignmentByUserAndMarina = `-- name: GetUserMarinaAssignmentByUserAndMarina :one
SELECT role_id, customer_id
FROM user_marinas
WHERE user_id = $1 AND marina_id = $2
`

type GetUserMarinaAssignmentByUserAndMarinaParams struct {
	UserID   uuid.UUID
	MarinaID uuid.UUID
}

type GetUserMarinaAssignmentByUserAndMarinaRow struct {
	RoleID     uuid.UUID
	CustomerID *string
}

func (q *Queries) GetUserMarinaAssignmentByUserAndMarina(ctx context.Context, arg GetUserMarinaAssignmentByUserAndMarinaParams) (GetUserMarinaAssignmentByUserAndMarinaRow, error) {
	row := q.db.QueryRow(ctx, getUserMarinaAssignmentByUserAndMarina, arg.UserID, arg.MarinaID)
	var i GetUserMarinaAssignmentByUserAndMarinaRow
	err := row.Scan(&i.RoleID, &i.CustomerID)
	return i, err
}

const getUserMarinasList = `-- name: GetUserMarinasList :many
SELECT m.id, m.organization_id, m.name, m.email, m.location, m.phone, m.country, m.currency, m.working_hours, m.website, m.image, m.max_users, m.is_active, m.is_test, m.created_at, m.updated_at, m.deleted_at, m.address_id, m.system_id, m.storage_usage, m.email_usage, m.text_usage, m.notes_messages_plan_id, m.storage_plan_id, m.modules, m.internal_announcement, m.external_announcement, m.document_plan_id, m.document_usage
FROM marinas m
    JOIN user_marinas um ON m.id = um.marina_id
WHERE um.user_id = $1
    AND m.deleted_at IS NULL
`

func (q *Queries) GetUserMarinasList(ctx context.Context, userID uuid.UUID) ([]Marina, error) {
	rows, err := q.db.Query(ctx, getUserMarinasList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Marina
	for rows.Next() {
		var i Marina
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Email,
			&i.Location,
			&i.Phone,
			&i.Country,
			&i.Currency,
			&i.WorkingHours,
			&i.Website,
			&i.Image,
			&i.MaxUsers,
			&i.IsActive,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AddressID,
			&i.SystemID,
			&i.StorageUsage,
			&i.EmailUsage,
			&i.TextUsage,
			&i.NotesMessagesPlanID,
			&i.StoragePlanID,
			&i.Modules,
			&i.InternalAnnouncement,
			&i.ExternalAnnouncement,
			&i.DocumentPlanID,
			&i.DocumentUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMarinasListPaginated = `-- name: GetUserMarinasListPaginated :many
SELECT m.id, m.organization_id, m.name, m.email, m.location, m.phone, m.country, m.currency, m.working_hours, m.website, m.image, m.max_users, m.is_active, m.is_test, m.created_at, m.updated_at, m.deleted_at, m.address_id, m.system_id, m.storage_usage, m.email_usage, m.text_usage, m.notes_messages_plan_id, m.storage_plan_id, m.modules, m.internal_announcement, m.external_announcement, m.document_plan_id, m.document_usage
FROM marinas m
    JOIN user_marinas um ON m.id = um.marina_id
WHERE um.user_id = $1
    AND m.deleted_at IS NULL
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserMarinasListPaginatedParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetUserMarinasListPaginated(ctx context.Context, arg GetUserMarinasListPaginatedParams) ([]Marina, error) {
	rows, err := q.db.Query(ctx, getUserMarinasListPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Marina
	for rows.Next() {
		var i Marina
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Email,
			&i.Location,
			&i.Phone,
			&i.Country,
			&i.Currency,
			&i.WorkingHours,
			&i.Website,
			&i.Image,
			&i.MaxUsers,
			&i.IsActive,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AddressID,
			&i.SystemID,
			&i.StorageUsage,
			&i.EmailUsage,
			&i.TextUsage,
			&i.NotesMessagesPlanID,
			&i.StoragePlanID,
			&i.Modules,
			&i.InternalAnnouncement,
			&i.ExternalAnnouncement,
			&i.DocumentPlanID,
			&i.DocumentUsage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleInMarina = `-- name: GetUserRoleInMarina :one
SELECT u.role_id
FROM users u
    JOIN user_marinas um ON u.id = um.user_id
WHERE u.id = $1
    AND um.marina_id = $2
    AND u.deleted_at IS NULL
`

type GetUserRoleInMarinaParams struct {
	ID       uuid.UUID
	MarinaID uuid.UUID
}

func (q *Queries) GetUserRoleInMarina(ctx context.Context, arg GetUserRoleInMarinaParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserRoleInMarina, arg.ID, arg.MarinaID)
	var role_id uuid.UUID
	err := row.Scan(&role_id)
	return role_id, err
}

const getUsersNotAssignedToMarinaPaginated = `-- name: GetUsersNotAssignedToMarinaPaginated :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics
FROM users u
WHERE u.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM user_marinas um
    WHERE um.user_id = u.id
      AND u.is_superuser = FALSE
      AND um.marina_id = $1
  )
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersNotAssignedToMarinaPaginatedParams struct {
	MarinaID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetUsersNotAssignedToMarinaPaginated(ctx context.Context, arg GetUsersNotAssignedToMarinaPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersNotAssignedToMarinaPaginated, arg.MarinaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersNotAssignedToMarinaPaginatedAdmin = `-- name: GetUsersNotAssignedToMarinaPaginatedAdmin :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics
FROM users u
WHERE u.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM user_marinas um
    WHERE um.user_id = u.id
      AND um.marina_id = $1
  )
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersNotAssignedToMarinaPaginatedAdminParams struct {
	MarinaID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetUsersNotAssignedToMarinaPaginatedAdmin(ctx context.Context, arg GetUsersNotAssignedToMarinaPaginatedAdminParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersNotAssignedToMarinaPaginatedAdmin, arg.MarinaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMarinasAssignmentsPaginated = `-- name: ListUserMarinasAssignmentsPaginated :many
SELECT um.user_id, um.marina_id, um.assigned_at, um.customer_id, um.role_id, u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM user_marinas um
JOIN users u ON u.id = um.user_id
LEFT JOIN roles r ON u.role_id = r.id
WHERE um.marina_id = $1
  AND ($2::bool IS NULL OR ($2 = TRUE AND um.customer_id IS NOT NULL) OR ($2 = FALSE AND um.customer_id IS NULL))
  AND u.is_superuser = FALSE
  AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserMarinasAssignmentsPaginatedParams struct {
	MarinaID uuid.UUID
	Column2  bool
	Limit    int32
	Offset   int32
}

type ListUserMarinasAssignmentsPaginatedRow struct {
	UserID              uuid.UUID
	MarinaID            uuid.UUID
	AssignedAt          pgtype.Timestamp
	CustomerID          *string
	RoleID              uuid.UUID
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID_2          uuid.UUID
	RoleID_2            uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID_2        *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) ListUserMarinasAssignmentsPaginated(ctx context.Context, arg ListUserMarinasAssignmentsPaginatedParams) ([]ListUserMarinasAssignmentsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listUserMarinasAssignmentsPaginated,
		arg.MarinaID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMarinasAssignmentsPaginatedRow
	for rows.Next() {
		var i ListUserMarinasAssignmentsPaginatedRow
		if err := rows.Scan(
			&i.UserID,
			&i.MarinaID,
			&i.AssignedAt,
			&i.CustomerID,
			&i.RoleID,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID_2,
			&i.RoleID_2,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID_2,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMarinasAssignmentsPaginatedAdmin = `-- name: ListUserMarinasAssignmentsPaginatedAdmin :many
SELECT um.user_id, um.marina_id, um.assigned_at, um.customer_id, um.role_id, u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM user_marinas um
JOIN users u ON u.id = um.user_id
LEFT JOIN roles r ON u.role_id = r.id
WHERE um.marina_id = $1
  AND ($2::bool IS NULL OR ($2 = TRUE AND um.customer_id IS NOT NULL) OR ($2 = FALSE AND um.customer_id IS NULL))
  AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserMarinasAssignmentsPaginatedAdminParams struct {
	MarinaID uuid.UUID
	Column2  bool
	Limit    int32
	Offset   int32
}

type ListUserMarinasAssignmentsPaginatedAdminRow struct {
	UserID              uuid.UUID
	MarinaID            uuid.UUID
	AssignedAt          pgtype.Timestamp
	CustomerID          *string
	RoleID              uuid.UUID
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID_2          uuid.UUID
	RoleID_2            uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID_2        *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) ListUserMarinasAssignmentsPaginatedAdmin(ctx context.Context, arg ListUserMarinasAssignmentsPaginatedAdminParams) ([]ListUserMarinasAssignmentsPaginatedAdminRow, error) {
	rows, err := q.db.Query(ctx, listUserMarinasAssignmentsPaginatedAdmin,
		arg.MarinaID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMarinasAssignmentsPaginatedAdminRow
	for rows.Next() {
		var i ListUserMarinasAssignmentsPaginatedAdminRow
		if err := rows.Scan(
			&i.UserID,
			&i.MarinaID,
			&i.AssignedAt,
			&i.CustomerID,
			&i.RoleID,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID_2,
			&i.RoleID_2,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID_2,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMarinasAssignmentsPaginatedAdminOnly = `-- name: ListUserMarinasAssignmentsPaginatedAdminOnly :many
SELECT um.user_id, um.marina_id, um.assigned_at, um.customer_id, um.role_id, u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM user_marinas um
JOIN users u ON u.id = um.user_id
LEFT JOIN roles r ON u.role_id = r.id
WHERE um.marina_id = $1
  AND u.is_superuser = TRUE 
  AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserMarinasAssignmentsPaginatedAdminOnlyParams struct {
	MarinaID uuid.UUID
	Limit    int32
	Offset   int32
}

type ListUserMarinasAssignmentsPaginatedAdminOnlyRow struct {
	UserID              uuid.UUID
	MarinaID            uuid.UUID
	AssignedAt          pgtype.Timestamp
	CustomerID          *string
	RoleID              uuid.UUID
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID_2          uuid.UUID
	RoleID_2            uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID_2        *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) ListUserMarinasAssignmentsPaginatedAdminOnly(ctx context.Context, arg ListUserMarinasAssignmentsPaginatedAdminOnlyParams) ([]ListUserMarinasAssignmentsPaginatedAdminOnlyRow, error) {
	rows, err := q.db.Query(ctx, listUserMarinasAssignmentsPaginatedAdminOnly, arg.MarinaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMarinasAssignmentsPaginatedAdminOnlyRow
	for rows.Next() {
		var i ListUserMarinasAssignmentsPaginatedAdminOnlyRow
		if err := rows.Scan(
			&i.UserID,
			&i.MarinaID,
			&i.AssignedAt,
			&i.CustomerID,
			&i.RoleID,
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID_2,
			&i.RoleID_2,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID_2,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignUserFromMarina = `-- name: UnassignUserFromMarina :exec
DELETE FROM user_marinas
WHERE user_id = $1
    AND marina_id = $2
`

type UnassignUserFromMarinaParams struct {
	UserID   uuid.UUID
	MarinaID uuid.UUID
}

func (q *Queries) UnassignUserFromMarina(ctx context.Context, arg UnassignUserFromMarinaParams) error {
	_, err := q.db.Exec(ctx, unassignUserFromMarina, arg.UserID, arg.MarinaID)
	return err
}

const userCanAccessMarina = `-- name: UserCanAccessMarina :one
SELECT EXISTS (
    SELECT 1
    FROM user_marinas um
    WHERE um.user_id = $1
        AND um.marina_id = $2
) AS can_access
`

type UserCanAccessMarinaParams struct {
	UserID   uuid.UUID
	MarinaID uuid.UUID
}

func (q *Queries) UserCanAccessMarina(ctx context.Context, arg UserCanAccessMarinaParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanAccessMarina, arg.UserID, arg.MarinaID)
	var can_access bool
	err := row.Scan(&can_access)
	return can_access, err
}
