// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :one
UPDATE users
SET is_active = TRUE
WHERE id = $1
RETURNING id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
`

func (q *Queries) ActivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, activateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const countUsersWithFilters = `-- name: CountUsersWithFilters :one
SELECT COUNT(*)
FROM users
WHERE deleted_at IS NULL
  AND (
    $1 = '' 
    OR username ILIKE '%' || $1 || '%'
    OR first_name ILIKE '%' || $1 || '%'
    OR last_name ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
    OR phone ILIKE '%' || $1 || '%'
    OR title ILIKE '%' || $1 || '%'
  )
  AND ($2 = '' OR role_id = $2::uuid)
  AND ($3 = '' OR is_active = ($3)::boolean)
`

type CountUsersWithFiltersParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) CountUsersWithFilters(ctx context.Context, arg CountUsersWithFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithFilters, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomerUser = `-- name: CreateCustomerUser :one
INSERT INTO users (
        username,
        first_name,
        last_name,
        email,
        email_verified,
        phone,
        title,
        image,
        password_hash,
        last_login,
        failed_login_attempts,
        locked_until,
        last_password_reset,
        organization_id,
        marina_id,
        role_id,
        customer_id,
        is_customer,
        is_superuser,
        is_active,
        user_analytics
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21
    )
RETURNING id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
`

type CreateCustomerUserParams struct {
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	CustomerID          *string
	IsCustomer          *bool
	IsSuperuser         *bool
	IsActive            *bool
	UserAnalytics       *bool
}

func (q *Queries) CreateCustomerUser(ctx context.Context, arg CreateCustomerUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createCustomerUser,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.Title,
		arg.Image,
		arg.PasswordHash,
		arg.LastLogin,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.LastPasswordReset,
		arg.OrganizationID,
		arg.MarinaID,
		arg.RoleID,
		arg.CustomerID,
		arg.IsCustomer,
		arg.IsSuperuser,
		arg.IsActive,
		arg.UserAnalytics,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
        username,
        first_name,
        last_name,
        email,
        email_verified,
        phone,
        title,
        image,
        password_hash,
        last_login,
        failed_login_attempts,
        locked_until,
        last_password_reset,
        organization_id,
        marina_id,
        role_id,
        is_superuser,
        is_active,
        user_analytics
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19
    )
RETURNING id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
`

type CreateUserParams struct {
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	UserAnalytics       *bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.Title,
		arg.Image,
		arg.PasswordHash,
		arg.LastLogin,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.LastPasswordReset,
		arg.OrganizationID,
		arg.MarinaID,
		arg.RoleID,
		arg.IsSuperuser,
		arg.IsActive,
		arg.UserAnalytics,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active = FALSE
WHERE id = $1
RETURNING id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersFilteredSortedAsc = `-- name: GetAllUsersFilteredSortedAsc :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE deleted_at IS NULL
  AND (
    $1 = '' 
    OR username ILIKE '%' || $1 || '%'
    OR first_name ILIKE '%' || $1 || '%'
    OR last_name ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
    OR phone ILIKE '%' || $1 || '%'
    OR title ILIKE '%' || $1 || '%'
  )
  AND ($2 = '' OR role_id = $2::uuid)
  AND ($3 = '' OR is_active = ($3)::boolean)
ORDER BY
  (CASE WHEN $4 = 'username' THEN username END) ASC,
  (CASE WHEN $4 = 'first_name' THEN first_name END) ASC,
  (CASE WHEN $4 = 'last_name' THEN last_name END) ASC,
  (CASE WHEN $4 = 'email' THEN email END) ASC,
  (CASE WHEN $4 = 'phone' THEN phone END) ASC,
  (CASE WHEN $4 = 'title' THEN title END) ASC,
  (CASE WHEN $4 = 'last_login' THEN last_login END) ASC,
  (CASE WHEN $4 = 'failed_login_attempts' THEN failed_login_attempts END) ASC,
  (CASE WHEN $4 = 'locked_until' THEN locked_until END) ASC,
  (CASE WHEN $4 = 'last_password_reset' THEN last_password_reset END) ASC,
  (CASE WHEN $4 = 'created_at' THEN created_at END) ASC,
  (CASE WHEN $4 = 'updated_at' THEN updated_at END) ASC
LIMIT $5 OFFSET $6
`

type GetAllUsersFilteredSortedAscParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) GetAllUsersFilteredSortedAsc(ctx context.Context, arg GetAllUsersFilteredSortedAscParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsersFilteredSortedAsc,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersFilteredSortedDesc = `-- name: GetAllUsersFilteredSortedDesc :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE deleted_at IS NULL
  AND (
    $1 = '' 
    OR username ILIKE '%' || $1 || '%'
    OR first_name ILIKE '%' || $1 || '%'
    OR last_name ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
    OR phone ILIKE '%' || $1 || '%'
    OR title ILIKE '%' || $1 || '%'
  )
  AND ($2 = '' OR role_id = $2::uuid)
  AND ($3 = '' OR is_active = ($3)::boolean)
ORDER BY
  (CASE WHEN $4 = 'username' THEN username END) DESC,
  (CASE WHEN $4 = 'first_name' THEN first_name END) DESC,
  (CASE WHEN $4 = 'last_name' THEN last_name END) DESC,
  (CASE WHEN $4 = 'email' THEN email END) DESC,
  (CASE WHEN $4 = 'phone' THEN phone END) DESC,
  (CASE WHEN $4 = 'title' THEN title END) DESC,
  (CASE WHEN $4 = 'last_login' THEN last_login END) DESC,
  (CASE WHEN $4 = 'failed_login_attempts' THEN failed_login_attempts END) DESC,
  (CASE WHEN $4 = 'locked_until' THEN locked_until END) DESC,
  (CASE WHEN $4 = 'last_password_reset' THEN last_password_reset END) DESC,
  (CASE WHEN $4 = 'created_at' THEN created_at END) DESC,
  (CASE WHEN $4 = 'updated_at' THEN updated_at END) DESC
LIMIT $5 OFFSET $6
`

type GetAllUsersFilteredSortedDescParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) GetAllUsersFilteredSortedDesc(ctx context.Context, arg GetAllUsersFilteredSortedDescParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsersFilteredSortedDesc,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersPaginated = `-- name: GetAllUsersPaginated :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllUsersPaginated(ctx context.Context, arg GetAllUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaCustomerUserByCustomerIDPaginated = `-- name: GetMarinaCustomerUserByCustomerIDPaginated :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE is_customer = TRUE
    AND marina_id = $1
    AND customer_id = $2
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetMarinaCustomerUserByCustomerIDPaginatedParams struct {
	MarinaID   uuid.UUID
	CustomerID *string
	Limit      int32
	Offset     int32
}

func (q *Queries) GetMarinaCustomerUserByCustomerIDPaginated(ctx context.Context, arg GetMarinaCustomerUserByCustomerIDPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getMarinaCustomerUserByCustomerIDPaginated,
		arg.MarinaID,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaCustomerUsers = `-- name: GetMarinaCustomerUsers :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE marina_id = $1
    AND is_customer = TRUE
    AND deleted_at IS NULL
`

func (q *Queries) GetMarinaCustomerUsers(ctx context.Context, marinaID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getMarinaCustomerUsers, marinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaCustomerUsersByCustomerID = `-- name: GetMarinaCustomerUsersByCustomerID :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE is_customer = TRUE
    AND marina_id = $1
    AND customer_id = $2
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetMarinaCustomerUsersByCustomerIDParams struct {
	MarinaID   uuid.UUID
	CustomerID *string
}

func (q *Queries) GetMarinaCustomerUsersByCustomerID(ctx context.Context, arg GetMarinaCustomerUsersByCustomerIDParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getMarinaCustomerUsersByCustomerID, arg.MarinaID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarinaCustomerUsersPaginated = `-- name: GetMarinaCustomerUsersPaginated :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE is_customer = TRUE
    AND marina_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMarinaCustomerUsersPaginatedParams struct {
	MarinaID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetMarinaCustomerUsersPaginated(ctx context.Context, arg GetMarinaCustomerUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getMarinaCustomerUsersPaginated, arg.MarinaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE email = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const getUserByEmailAndOrg = `-- name: GetUserByEmailAndOrg :one
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE email = $1
    AND organization_id = $2
    AND deleted_at IS NULL
`

type GetUserByEmailAndOrgParams struct {
	Email          string
	OrganizationID uuid.UUID
}

func (q *Queries) GetUserByEmailAndOrg(ctx context.Context, arg GetUserByEmailAndOrgParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAndOrg, arg.Email, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE username = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const getUserByUsernameAndOrg = `-- name: GetUserByUsernameAndOrg :one
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE username = $1
    AND organization_id = $2
    AND deleted_at IS NULL
`

type GetUserByUsernameAndOrgParams struct {
	Username       string
	OrganizationID uuid.UUID
}

func (q *Queries) GetUserByUsernameAndOrg(ctx context.Context, arg GetUserByUsernameAndOrgParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameAndOrg, arg.Username, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const getUsersByMarina = `-- name: GetUsersByMarina :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.is_superuser = FALSE
    AND u.deleted_at IS NULL
`

type GetUsersByMarinaParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
}

type GetUsersByMarinaRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetUsersByMarina(ctx context.Context, arg GetUsersByMarinaParams) ([]GetUsersByMarinaRow, error) {
	rows, err := q.db.Query(ctx, getUsersByMarina, arg.MarinaID, arg.IsCustomer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByMarinaRow
	for rows.Next() {
		var i GetUsersByMarinaRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByMarinaAdmin = `-- name: GetUsersByMarinaAdmin :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.deleted_at IS NULL
`

type GetUsersByMarinaAdminParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
}

type GetUsersByMarinaAdminRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetUsersByMarinaAdmin(ctx context.Context, arg GetUsersByMarinaAdminParams) ([]GetUsersByMarinaAdminRow, error) {
	rows, err := q.db.Query(ctx, getUsersByMarinaAdmin, arg.MarinaID, arg.IsCustomer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByMarinaAdminRow
	for rows.Next() {
		var i GetUsersByMarinaAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByMarinaPaginated = `-- name: GetUsersByMarinaPaginated :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.is_superuser = FALSE
    AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUsersByMarinaPaginatedParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
	Limit      int32
	Offset     int32
}

type GetUsersByMarinaPaginatedRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetUsersByMarinaPaginated(ctx context.Context, arg GetUsersByMarinaPaginatedParams) ([]GetUsersByMarinaPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getUsersByMarinaPaginated,
		arg.MarinaID,
		arg.IsCustomer,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByMarinaPaginatedRow
	for rows.Next() {
		var i GetUsersByMarinaPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByMarinaPaginatedAdmin = `-- name: GetUsersByMarinaPaginatedAdmin :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUsersByMarinaPaginatedAdminParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
	Limit      int32
	Offset     int32
}

type GetUsersByMarinaPaginatedAdminRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetUsersByMarinaPaginatedAdmin(ctx context.Context, arg GetUsersByMarinaPaginatedAdminParams) ([]GetUsersByMarinaPaginatedAdminRow, error) {
	rows, err := q.db.Query(ctx, getUsersByMarinaPaginatedAdmin,
		arg.MarinaID,
		arg.IsCustomer,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByMarinaPaginatedAdminRow
	for rows.Next() {
		var i GetUsersByMarinaPaginatedAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByMarinaUsersListPaginated = `-- name: GetUsersByMarinaUsersListPaginated :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
JOIN user_marinas um ON u.id = um.user_id
LEFT JOIN roles r ON u.role_id = r.id
WHERE um.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.is_superuser = FALSE
    AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUsersByMarinaUsersListPaginatedParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
	Limit      int32
	Offset     int32
}

type GetUsersByMarinaUsersListPaginatedRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetUsersByMarinaUsersListPaginated(ctx context.Context, arg GetUsersByMarinaUsersListPaginatedParams) ([]GetUsersByMarinaUsersListPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getUsersByMarinaUsersListPaginated,
		arg.MarinaID,
		arg.IsCustomer,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByMarinaUsersListPaginatedRow
	for rows.Next() {
		var i GetUsersByMarinaUsersListPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByMarinaUsersListPaginatedAdmin = `-- name: GetUsersByMarinaUsersListPaginatedAdmin :many
SELECT u.id, u.username, u.first_name, u.last_name, u.email, u.email_verified, u.phone, u.title, u.image, u.password_hash, u.last_login, u.failed_login_attempts, u.locked_until, u.last_password_reset, u.organization_id, u.marina_id, u.role_id, u.is_superuser, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.customer_id, u.is_customer, u.joined_at, u.user_analytics, r.name as role_name
FROM users u
JOIN user_marinas um ON u.id = um.user_id
LEFT JOIN roles r ON u.role_id = r.id
WHERE um.marina_id = $1
    AND (u.is_customer = $2 OR $2 IS NULL)
    AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUsersByMarinaUsersListPaginatedAdminParams struct {
	MarinaID   uuid.UUID
	IsCustomer *bool
	Limit      int32
	Offset     int32
}

type GetUsersByMarinaUsersListPaginatedAdminRow struct {
	ID                  uuid.UUID
	Username            string
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	OrganizationID      uuid.UUID
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
	CustomerID          *string
	IsCustomer          *bool
	JoinedAt            pgtype.Timestamp
	UserAnalytics       *bool
	RoleName            *string
}

func (q *Queries) GetUsersByMarinaUsersListPaginatedAdmin(ctx context.Context, arg GetUsersByMarinaUsersListPaginatedAdminParams) ([]GetUsersByMarinaUsersListPaginatedAdminRow, error) {
	rows, err := q.db.Query(ctx, getUsersByMarinaUsersListPaginatedAdmin,
		arg.MarinaID,
		arg.IsCustomer,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByMarinaUsersListPaginatedAdminRow
	for rows.Next() {
		var i GetUsersByMarinaUsersListPaginatedAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganization = `-- name: GetUsersByOrganization :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE organization_id = $1
    AND is_superuser = FALSE
    AND deleted_at IS NULL
`

func (q *Queries) GetUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganizationAdmin = `-- name: GetUsersByOrganizationAdmin :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE organization_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUsersByOrganizationAdmin(ctx context.Context, organizationID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByOrganizationAdmin, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganizationPaginated = `-- name: GetUsersByOrganizationPaginated :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE organization_id = $1
    AND is_superuser = FALSE
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersByOrganizationPaginatedParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetUsersByOrganizationPaginated(ctx context.Context, arg GetUsersByOrganizationPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByOrganizationPaginated, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganizationPaginatedAdmin = `-- name: GetUsersByOrganizationPaginatedAdmin :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE organization_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersByOrganizationPaginatedAdminParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetUsersByOrganizationPaginatedAdmin(ctx context.Context, arg GetUsersByOrganizationPaginatedAdminParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByOrganizationPaginatedAdmin, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE role_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUsersByRole(ctx context.Context, roleID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRolePaginated = `-- name: GetUsersByRolePaginated :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE role_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersByRolePaginatedParams struct {
	RoleID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetUsersByRolePaginated(ctx context.Context, arg GetUsersByRolePaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRolePaginated, arg.RoleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersPaginated = `-- name: GetUsersPaginated :many
SELECT id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetUsersPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetUsersPaginated(ctx context.Context, arg GetUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.EmailVerified,
			&i.Phone,
			&i.Title,
			&i.Image,
			&i.PasswordHash,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastPasswordReset,
			&i.OrganizationID,
			&i.MarinaID,
			&i.RoleID,
			&i.IsSuperuser,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerID,
			&i.IsCustomer,
			&i.JoinedAt,
			&i.UserAnalytics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = $2,
    last_name = $3,
    email = $4,
    email_verified = $5,
    phone = $6,
    title = $7,
    image = $8,
    password_hash = $9,
    last_login = $10,
    failed_login_attempts = $11,
    locked_until = $12,
    last_password_reset = $13,
    marina_id = $14,
    role_id = $15,
    is_superuser = $16,
    is_active = $17,
    user_analytics = $18,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
`

type UpdateUserParams struct {
	ID                  uuid.UUID
	FirstName           string
	LastName            string
	Email               string
	EmailVerified       pgtype.Timestamp
	Phone               *string
	Title               *string
	Image               *string
	PasswordHash        *string
	LastLogin           pgtype.Timestamp
	FailedLoginAttempts *int32
	LockedUntil         pgtype.Timestamp
	LastPasswordReset   pgtype.Timestamp
	MarinaID            uuid.UUID
	RoleID              uuid.UUID
	IsSuperuser         *bool
	IsActive            *bool
	UserAnalytics       *bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.Title,
		arg.Image,
		arg.PasswordHash,
		arg.LastLogin,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.LastPasswordReset,
		arg.MarinaID,
		arg.RoleID,
		arg.IsSuperuser,
		arg.IsActive,
		arg.UserAnalytics,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}

const updateUserInvite = `-- name: UpdateUserInvite :one
UPDATE users
SET password_hash = $2,
    last_password_reset = CURRENT_TIMESTAMP,
    failed_login_attempts = 0,
    joined_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, first_name, last_name, email, email_verified, phone, title, image, password_hash, last_login, failed_login_attempts, locked_until, last_password_reset, organization_id, marina_id, role_id, is_superuser, is_active, created_at, updated_at, deleted_at, customer_id, is_customer, joined_at, user_analytics
`

type UpdateUserInviteParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdateUserInvite(ctx context.Context, arg UpdateUserInviteParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInvite, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.Title,
		&i.Image,
		&i.PasswordHash,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastPasswordReset,
		&i.OrganizationID,
		&i.MarinaID,
		&i.RoleID,
		&i.IsSuperuser,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerID,
		&i.IsCustomer,
		&i.JoinedAt,
		&i.UserAnalytics,
	)
	return i, err
}
