name: Deploy Go Backend DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy and Run Container
        run: |
          docker run -d -p 8080:8080 \
            -e DB_HOST=${{ secrets.AWS_RDS_DEV_HOST }} \
            -e DB_PORT=${{ secrets.AWS_RDS_DEV_PORT }} \
            -e DB_USER=${{ secrets.AWS_RDS_DEV_USER }} \
            -e DB_PASSWORD=${{ secrets.AWS_RDS_DEV_PASSWORD }} \
            -e DB_NAME=${{ secrets.AWS_RDS_DEV_NAME }} \
            $IMAGE_URI
